# -*- coding: utf-8 -*-
"""daemi_yfir_onnina_fyrirlestrar.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L3bmkKweJAKZ1K-b7Q2ajFb2Ma6YfVeK
"""

x = 2
s = "AB"

print(x, s, end="; ")
print(x*2, s*2, end=";")





x = 2
s = "AB"

print(x, s, sep=",", end="; ")
print(x*2, s*2, sep=",", end=";")

import math
def rummal(h,r):
  f = math.pi*r**2*h/3
  return f



print(rummal(4,3))

def flat_og_um(r):
    pi = 3.14159265
    F = r**2*pi
    U = 2*r*pi
    return F,U

(F,U) = flat_og_um(1)
print(f"Flatarmálið er {F:.2f} og ummálið {U:.3f}")

x = -3
y = 2.7
s = "abc"

print(abs(x))  # |x|
print(max(x, y))  # max(x, y)
print(min(x, y))  # min(x, y)
print(float(x))  # float(x)
print(int(y))  # int(y)
print(list(range(4)))  # range(4)
print(len(s))  # len(s)
print(type(s))  # type(s)

print(type(s))
display(type(s))
display(list(range(4)))

import math
def sveifla(m,k1,k2):
  return 2*math.pi*math.sqrt(m/(k1+k2))
F = sveifla(2,3,4)
print(f"Sveifla er {F:.3f}")

def trap1(f, a, b):
    h = (b - a) / 2
    return h * (f(a) + f(b))

def trap2(f, a, b):
    m = (a + b) / 2
    return trap1(f, a, m) + trap1(f, m, b)

# Prófun með fallið f(x) = x^2 og bilin a = 0 og b = 1
def f(x):
    return x**2

a = 0
b = 1

I1 = trap1(f, a, b)
I2 = trap2(f, a, b)

print("I1 =", I1)
print("I2 =", I2)

import math
print('x     √x     x²')
print('―――――――――――――――')
for x in range(2,6):
    print(f'{x}   {math.sqrt(x):.4f}   {x**2:2}')

import math
print('x     √x     x²')
print('―――――――――――――――')
n = 3
for x in range(2,6):
    print(f'{x}   {math.sqrt(x):.{n}f}   {x**2:2}')

def reikna(x):
  if x <1:
    f= x**2
  else:
    f= 2*x-1
  return f

print(reikna(0))
print(reikna(3))

def reikna(k):
  f= 9/5*k + 32
  return f

print(" C°      F°")
print("–––––––––––")
for k in range(-30,51,5):
  print(f"{k:2} {reikna(k):2}")

import math
def kvad(x):
  return math.sqrt(x)
def logri(x):
  return math.log(x)
def annaveldi(x):
  return x**2

for x in range(1,11):
  print(kvad(x),logri(x),annaveldi(x))

import math
def kvad(x):
  return math.sqrt(x)
def logri(x):
  return math.log(x)
def annaveldi(x):
  return x**2

x=1
while x<11:
  print(kvad(x),logri(x),annaveldi(x))
  x+=1

"""Til að reikna logra (lógaritma) hefur Python þrjú föll: Náttúrulegur logri fæst með log(x), tíu-logri fæst með log10(x) og loks fæst logri með grunntölu 2 með log2(x). Fastinn 𝑒
e
 fæst með math.e, og vísisfallið, 𝑒𝑥
e
x
, fæst með exp(x). Reiknið:

ln(1)
ln
⁡
(
1
)
lnexp(3)
ln
⁡
exp
⁡
(
3
)
log101000
log
10
⁡
1000
log28
"""

import math
def loggi(x):
  return math.log(x)

print(loggi(1))
print(math.log(math.exp(3)))
print(math.log10(1000))
print(math.log2(8))

def radkula(r):
  return 4*math.pi*r**3/3
x=2
print(radkula(x))

def kularad(c):
  return c/(2*math.pi)

print(kularad(33.51))

def mass(density,volume):
  dennsityToMetric = density*1000
  mass = dennsityToMetric * (volume)
  return mass
print(f"The mass is {round(mass(19.30,(20/100)**3),3)}"+f" kg")

print(mass(40))

def trap1(f,a,b,n):
  dx = (b-a)/n
  sum=0
  for i in range(1,n):
    xi = a+ i*dx
    (x0,xn) = (a,b)




from math import sin, e
def g(x): return sin(x)/x
def h(x): return e**x

n=4
I1 = trap1(g,1,2,n)
I2 = trap1(g,0,1,n)
print(f'I1={I1:.3f}, I2={I2:.3f}')
    # prentar "I1=0.648, I2=1.859"

def sqrt(a):
    x = 1.0  # Upphafsgildi
    epsilon = 1e-4  # Lögmæti (t.d. 10^-4)

    while True:
        y = (x + a / x) / 2
        if abs(x - y) < epsilon:
            return y
        x = y

# Prófið að reikna kvaðratrót af 9 og 10
print(sqrt(9))
print(sqrt(10))

def trap1(f, a, b):
    return (b - a) * (f(a) + f(b)) / 2

def trap2(f, a, b):
    m = (a + b) / 2
    return trap1(f, a, m) + trap1(f, m, b)

# Prófið að nálga sömu heildi með trap2
def f(x):
    return x**3 - x**2 + x

I1 = trap2(f, 0, 1)
I2 = trap2(f, 1, 2)

print(I1)
print(I2)

import math
print('x     √x     x²')
print('―――――――――――――――')
for x in range(0,7,2):
    print(f'{x}   {math.sqrt(x):.4f}   {x**2:2}')

import math
print('x     √x     x²')
print('―――――――――――――――')
n=5
for x in range(0,7,2):
    print(f'{x}   {math.sqrt(x):.{n}f}   {x**2:2}')

def reikna(x):
  if x < 1:
    x= x**2
  else:
    x= 2*x-1
  return x
t= reikna(0)
s = reikna(3)
print(t)
print(s)

s = "thor sanchez"
s.find(" ")

s = "thor sanchez"
t= s[0:4]

s = "hor sanchez"
len(t)

s = "hor sanchez"
if t in s.lower():
  print("the name contains t")
else:
  print("nahh")

def haus(L):
  return L[0]

def hali(L):
  return L[-1]

L= [1,2,3,4,5,7,8]
print(haus(L))
print(hali(L))

def setjafremst(L,g):
  L.insert(0,g)

listi = [1,2,3,4,5,6]
print("upphaflegur listi", listi)
setjafremst(listi,87)
print("nýr listi", listi)

def oddalisti(L,n):
  for i in range(n):
    if i%2!=0:
      L.append(i)

listi = []
oddalisti(listi,10)
print("nyr fucking listi : ",listi)

s = set(range(2,21))
print(s)
M3 = set(range(3,19,3))
print(M3)
M5 = set(range(5,21,5))
print(M5)
M6 = s & M3
print(M6)

def tilskiptis(L1,L2):
  newnew=[]
  for i in range(len(L1)):
    newnew.append(L1[i]);
    newnew.append(L2[i])
  return newnew



tilskiptis([1, 3, 7],[2, 6, 8])

def tilskiptismis(L1,L2):
  newnew=[]
  for i in range(max(len(L1), len(L2))):
    if i < len(L1):
      newnew.append(L1[i])
    if i < len(L2):
      newnew.append(L2[i])
  return newnew

print(tilskiptismis([1, 3, 7, 9],[2, 6]))

def finnabila(T1, T2, nafn):
  pepe = []
  for (nr,eigandi) in T1.items():
    if T1[nr]==nafn:
      pepe.append(T2[nr])
  return pepe


T1 = {"MSS-42": "Elín", "ZH-474": "Kristján", "JVD-69": "Kristján"}
T2 = {"MSS-42": "Hyundai", "ZH-474": "Toyota", "JVD-69": "Volvo"}
finnabila(T1,T2,"Kristján")

def bilalisti2(T1, T2, nafn):
  fuckpepe = []
  for (nr,eigandi) in T1.items():
    if eigandi == nafn:
      if nr in T2:
        fuckpepe.append(T2[nr])
      else:
        fuckpepe.append("óþekkt tegund")
  return fuckpepe




T1 = {"MSS-42": "Elín", "ZH-474": "Kristján", "JVD-69": "Kristján"}
T2 = {"MSS-42": "Hyundai", "ZH-474": "Toyota"}
print(bilalisti2(T1,T2,"Jón"))
print(bilalisti2(T1,T2,"Kristján"))



X= set(range(2,21))

P = {x for x in X if x < 20 and x not in (X - (s | M3 | M5)) | {2,3,5}}
print(P)

E = {"Ari", "Ása", "Fía", "Jói"}
S = {"Fía", "Jói", "Nói"}
b = E & S
print("í báðum fögum: ", b)
c = E | S
print("í einhverju fagi: ", c)
d = E ^ S
print("í bara einu fagi: ", d)

import sys
x = range(1000)
y = list(range(1000))
print(sys.getsizeof(x))
print(sys.getsizeof(y))

def bolu(x):
  sorted = True
  while(sorted):
    sorted = False
    for i in range(1,len(x)):
      if (x[i-1] > x[i]):
        y = x[i-1]
        x[i-1] = x[i]
        x[i]= y
        sorted = True
x = [3,8,1,2,5,4]
bolu(x)
print(x)

def reikna(u,p,k,m):
  a= p/100
  v = u*(1 + a)**k * (1+(a*m)/12) - u
  return v

u = 1000
k = 0
p = 13
m = 1

print(reikna(10000,2,3,4))

def til_skiptis(L1,L2):
  pewpew = []
  for i in range(len(L1)):
    pewpew.append(L1[i])
    pewpew.append(L2[i])
  return pewpew


print(til_skiptis([1, 3, 7], [2, 6, 8]))

def til_skiptismis(L1,L2):
  pewpew = []
  for i in range(max(len(L1),len(L2))):
    if i < len(L1):
      pewpew.append(L1[i])
    if i < len(L2):
      pewpew.append(L2[i])
  return pewpew


print(til_skiptismis([1, 3, 7, 9], [2, 6]))

def bilaeigandi(T1,T2,clown):
  pepe = []
  for(nr, eigandi) in T2.items():
    if T1[nr] == clown:
      pepe.append(eigandi)
  return pepe


T1 = {"MSS-42": "Elín", "ZH-474": "Kristján", "JVD-69": "Kristján"}
T2 = {"MSS-42": "Hyundai", "ZH-474": "Toyota", "JVD-69": "Volvo"}
svar = bilaeigandi(T1, T2, "Kristján")
print(svar)

def bilaeigandi(T1,T2,clown):
  pepe = []
  for(nr, eigandi) in T1.items():
    if eigandi == clown:
      if nr in T2:
        pepe.append(T2[nr])
      else:
        pepe.append("ikkje noe jævla model som er kjent her")
  return pepe


T1 = {"MSS-42": "Elín", "ZH-474": "Kristján", "JVD-69": "Kristján"}
T2 = {"MSS-42": "Hyundai", "ZH-474": "Toyota"}
svar = bilaeigandi(T1, T2, "Jón")
print(svar)
lala = bilaeigandi(T1, T2,"Kristján")
print(lala)



def bílalisti2(T1, T2, bíleigandi): L = []
for (nr, eigandi) in T1.items(): if eigandi == bíleigandi:
if nr in T2: L.append(T2[nr])
else:
L.append("óþekkt tegund")
return L
T3 = {"MSS-42": "Hyundai", "ZH-474": "Toyota"} print(bílalisti(T1, T3, "Jón")) print(bílalisti2(T1, T3, "Kristján"))

def reikna(u,p,k,m):
  a= p/100
  v = u*(1 + a)**k * (1+(a*m)/12) - u
  return v

u = 25000
k = 22
p = 3
m = 5

print(reikna(u,2,3,4))

def reikna(L,s):
  L[0]=s
  L[0]=L[-1]
  L[-1]=s
listi = [1,2,3,4]
print(listi)
reikna(listi)
print(listi)

def til_skiptist(L1,L2):
  L=[]
  for i in range(len(L1)):
    L.append(L1[i])
    L.append(L2[i])
  return L
print(til_skiptist([1,3,7],[2,6,8]))

def til_skiptist_mislangir(L1,L2):
  C=[]
  for i in range(max(len(L1),len(L2))):
    if i < len(L1):
      C.append(L1[i])
    if i < len(L2):
      C.append(L2[i])
  return C

A = [1,3,7,9]
B = [2,6]
print(til_skiptist_mislangir(A,B))

def finnabíla(T1,T2, nafn):
  A=[]
  for (nr,tegund) in T1.items():
    if T1[nr]==nafn:
      A.append(tegund)
  return A

T1 = {"MSS-42": "Elín", "ZH-474": "Kristján", "JVD-69": "Kristján"}
T2 = {"MSS-42": "Hyundai", "ZH-474": "Toyota", "JVD-69": "Volvo"}
finnabíla(T1, T2, "Kristján")

def hausaftast(L):
    return L[1:] + [L[0]]

# Prófið
L = [1, 2, 3, 4]
nyr_listi = hausaftast(L)
print("Nýi listinn:", nyr_listi)

def snúavið(L):
  n = len(L)
  M = []
  for i in range(n-1,-1,-1):
    M.append(L[i])
  return M
print('Liður 3:')
print(snúavið(L))
print(snúavið([17,8,58]))

isl_ens = {"reipi":"rope", "hús": "house", "rauður":"red", "tómarúm":"vaccum",
"ryksuga": "vaccum"}

def switchup(U):
  return {v:k for k, v in U.items()}

def snúavið2(U):
    V = {}
    for key in U:
        value = U[key]
        if value not in V:
            V[value] = [key]
        else:
            V[value].append(key)
    return V

print(snúavið2(isl_ens))

def tilskiptist(L,F):
  A= []
  for i in range(len(L)):
    A.append(L[i])
    A.append(F[i])
  return A
tilskiptist([1,3,7], [2,6,8])

def til_skiptis_mislangir(L1, L2):
  L = []
  for i in range(max(len(L1), len(L2))):
    if i < len(L1):
      L.append(L1[i])
    if i < len(L2):
      L.append(L2[i])
  return L
til_skiptis_mislangir([1,3,7,9], [2,6])

def finnabíla(T1,T2,nafn):
  A= []
  for (nr,bilategund) in T2.items():
    if T1[nr] == nafn:
      A.append(bilategund)
  return A


T1 = {"MSS-42": "Elín", "ZH-474": "Kristján", "JVD-69": "Kristján"}
T2 = {"MSS-42": "Hyundai", "ZH-474": "Toyota", "JVD-69": "Volvo"}
finnabíla(T1, T2, "Kristján")

def bílalísti2(T1,T2,nafn):
  A = []
  for(nr,eigandi) in T1.items():
    if eigandi == nafn:
      if nr in T2:
        A.append(T2[nr])
      else:
        A.append("óþekkt tegund")
  return A


T1 = {"MSS-42": "Elín", "ZH-474": "Kristján", "JVD-69": "Kristján"}
T2 = {"MSS-42": "Hyundai", "ZH-474": "Toyota"}

print(bílalísti2(T1,T2,"Jón"))
print(bílalísti2(T1,T2,"Kristján"))

def sameining(T1, T2):
  T = {}
  for (nr, eigandi) in T1.items():
    tegund = T2[nr]
    T[nr] = tegund + " sem " + eigandi + " á"
  return T
T1 = {"MSS-42": "Elín", "ZH-474": "Kristján", "JVD-69": "Kristján"}
T2 = {"MSS-42": "Hyundai", "ZH-474": "Toyota", "JVD-69": "Volvo"}
sameining(T1, T2)

def reikna(T1,T2):
    T ={}
    for(nr,eigandi) in T1.items():
        tegund = T2[nr]
        T[nr]=tegund + " sem " + eigandi + " a"
    return T

print(reikna(T1,T2))

T1 = {"MSS-42": "Elín", "ZH-474": "Kristján", "JVD-69": "Kristján"}
T2 = {"MSS-42": "Hyundai", "ZH-474": "Toyota", "JVD-69": "Volvo"}

def sameining2(T1, T2):
    T = {}
    númeramengi = set(T1.keys()) | set(T2.keys())
    for nr in númeramengi:
        s = T2.get(nr, "Óþekkt tegund")
        if nr in T1:
            s += " sem " + T1[nr] + " á"
        else:
            s += " með óþekktan eiganda"
        T[nr] = s
    return T
T1 = {"MSS-42": "Elín", "ZH-474": "Kristján", "JVD-69": "Kristján", "XYZ-12": "Ari"}
T2 = {"MSS-42": "Hyundai", "ZH-474": "Toyota", "JVD-69": "Volvo", "AB-123": "Fiat"}
sameining2(T1, T2)

def finnabila(T1,T2,eigandi):
    pepe = []
    for (nr, bilaeigandi) in T2.items():
        if T1[nr] == eigandi:
            pepe.append(bilaeigandi)
    return pepe

T1 = {"MSS-42": "Elín", "ZH-474": "Kristján", "JVD-69": "Kristján"}
T2 = {"MSS-42": "Hyundai", "ZH-474": "Toyota", "JVD-69": "Volvo"}
finnabila(T1, T2, "Kristján")

E = enumerate([2,4,6,8,10])
print(list(E))

E = [2,4,6,8,10]
L = [0,1,3,5,7,9]
z = zip(L,E)
print(list(z))

nöfn = {"Ása", "Bjarni", "Dóra", "Einar"}
eink = [8,7,10,9]
print("NR.  NAFN.  EINKUNN")
print("-------------------")
for nr,(nafn,einkunn) in enumerate(zip(nöfn,eink),1):
  print(f"{nr:1} {nafn:7} {einkunn:2}")

s = [2,5,6,8,3,9,9]
t = tuple(s)
print(t)
m =set(s)
print(m)
ls= sorted(s)
print(ls)

print(list("abc"))

s= "Afi minn og amma mín"
L=s.split()
print(L)

L = ["halla", "balla"]
E = zip(L)
print(E)
print(list(E))

L=[1,2,3,5]
S={2,8,4}
print("minnsta:",min(L)," stærsta stak:",max(L)," summa stakanna:",sum(L))
print("minnsta:",min(S)," stærsta stak:",max(S)," summa stakanna:",sum(S))

S=[True, False, False]
L=[False, False]
Q=[True, True]
print(any(S))
print(any(L))
print(any(Q))
print(all(S))
print(all(L))
print(all(Q))

def meðx(M,x):
  T=[]
  for (i, Mi) in enumerate(M):
    xerstak = x in Mi
    T.append(xerstak)
  return T



M = [{0,1,2}, {1,2,3}, {2,3,4}]
x = 3
print(meðx(M,x))

S = "Rómverskur riddari réðst inn í Rómarborg, rændi þar og ruplaði radísum og rófum"
l=S.lower()
print(l.count("r"))

def reikna(L,S):
  for i in range(len(L)):
    if S in L:
      return L.index(S)
    else:
      return -1

L = [1,2,3]
print(reikna(L,4))

S1 = (1,2,3)
S2 = (1,2,3)
S3 = S1 + S2
print(S3)
S4 = (1,2,3)*2
print(S4)

L = list()
M = [7,8]
print(L.append(1))
print(L.append(2))    # Nú er L = [1,2]
print(L.extend(M))    # jafngilt og L = L + M eða L += M
print(L.remove(2))
print(M.pop())

S = [2,3,4,5,6,7]
S.insert(1,77)
print(S)

def reikna(L):
  for x in L:
    print(x)



L = ["Ari", "Ása", "Fía", "Jói", "Nói"]
reikna(L)

def reikna(L):
  for (i,x) in enumerate(L,1):
    print(i,x)

print(" nöfn")
print("-----")
L = ["Ari", "Ása", "Fía", "Jói", "Nói"]
reikna(L)

L = [2**k for k in range(1,11)]
print(L)

x = [3,4,0,2,0,8,5]
L = [k for k in x if k>0]
print(L)

def fletta(kt, K, N, S):
  T = {}
  if kt in K:
    index = K.index(kt)
    nafn = N[index]
    skuld = S[index]
    print(f"Nafn: {nafn}, Skuld: {skuld}")
  else:
    print("nononnononon")

K = ["170858-4259", "040302-0100", "101010-1010"]
N = ["Karl", "Eva", "Ari"]
S = ["3500 kr", "4600 kr", "3400 kr"]

print(fletta("170858-4259",K,N,S))
print(fletta("34123",K,N,S))

def f(x):
  return x**2 - 2*x

L = {0,1,2,3,4,5}
D = {x: f(x) for x in L}
print(D)

def reikna(kt,K,N,S):
  pepe = []
  if kt in K:
    index=K.index(kt)
    nafn =N[index]
    skuld = S[index]

    print(f"NAFN: {nafn}, SKULD: {skuld}")
  else:
    print(f"ERROR couldn´t find the social securitynr. : {kt}")






K = ["170858-4259", "040302-0100", "101010-1010"]
N = ["Karl", "Eva", "Ari"]
S = ["3500 kr", "4600 kr", "3400 kr"]
D= reikna("170858-4259",K,N,S)
W = 9898997
ST = reikna(W,K,N,S)
print(D)
print(ST)

def reikna(kt, T):
  pepe= []
  for nr, (nafn,skuld) in T.items():
    if kt == nr:
      return f"Nafn: {nafn}, skuld: {skuld}"


T = {'170858-4259': ('Karl', '3500 kr'), '040302-0100': ('Eva', '4600 kr'), '101010-1010': ('Ari', '3400 kr')}
print(reikna('170858-4259',T))

T = {"ca": "California",
     "ok": "Oklahoma",
     "nj": "New Jersey",
     "tx": "Texas"}
while True:
    skst = input("Sláðu inn skammstöfun (x til að hætta)").lower()
    if skst == "x": break
    if not skst in T:
        print("Óþekkt fylki")
    else:
        print(T[skst])
print("Kællfyrir")

print("skst  Fylki")
print("––––––––––––––––––")
for (skst, fylki) in T.items():
    print(skst, fylki)

city = ["Reykjavík", "Seltjarnarnes", "Mosfellsbær", "Kópavogur", "Garðabær", "Hafnarfjörður"]
pepe = city.sort()
print(pepe)

L = ["Reykjavík", "Seltjarnarnes", "Mosfellsbær", "Kópavogur", "Garðabær",  "Hafnarfjörður"]
L.sort()
print(L)

L = ["Reykjavík", "Seltjarnarnes", "Mosfellsbær", "Kópavogur", "Garðabær",  "Hafnarfjörður"]
L.sort()
pepe = {nr: L[nr-1] for nr in range(1,7)}
pepe

def telja(s):
  return [len(ord) for ord in s.split()]



st=telja("Afi minn og amma mín")
st

def telja(s):
  jaja = []
  pepe = s.split()
  for i in range(0,len(pepe)):
    jaja.append(len(pepe))




st=telja("Afi minn og amma mín")
st

def hropa(s):
  s= s.upper()
  print(f"{s} !!")


hropa("Thor Sanchez")

def hropa(s):
    s = s.title()
    print(f"{s} !!")

hropa("thor sanchez")

def reikna(S):
  return [ord[0].isupper() for ord in S.split()]

S = ("Afi minn og Amma mín")

print(reikna(S))

import math
def reikna(f,a,h):
  return (((f(a+h))-(f(a-h)))/(2*h))

def f(x):
  return math.sqrt(x)
h = math.pow(10,-4)
a = 4
reikna(f,a,h)

import math
a=4
h=math.pow(10,(-4))
def f(x):
return math.sqrt(x)
def töldiff(f, a, h):
return (((f(a+h))-(f(a-h)))/(2*h))
k_4 = töldiff(f,a,h)
print(k_4)

isl_ens = {
"reipi": "rope",
"hús": "house",
"rauður":"red"
}

def snuavið(u):
  return {v: k for (k, v) in u.items()}

st = snuavið(isl_ens)
print(st)

# 2
isl_ens = {
"reipi": "rope",
"hús": "house",
"rauður":"red",
"tómarúm":"vaccum",
"ryksuga":"vaccum"
}


def snúavið2(U):
  V = {}
  for k, v in U.items():
    V.setdefault(v,[]).append(k)
  return V
ens_isl = snúavið2(isl_ens)
print(ens_isl)

print("1. Liður")
from urllib.request import urlopen

f = urlopen("https://cs.hi.is/python/ord.txt")
orðalisti = []

for lína in f:
    orð = lína.decode().strip()
    orðalisti.append(orð)

print("-------------Fyrstu 5--------------")
for i in range(6):
    print(orðalisti[i])

print("------Hvert tíuþúsundasta orð------")
for i in range(9999, len(orðalisti), 10000):
    print(orðalisti[i])

print("--------Lengri en 30 stafir--------")
for i in orðalisti:
    if len(i) > 30:
        print(i)

import numpy as np
import numpy.linalg as la
pepe = ([2,3,5,7,11])
print(len(pepe))
print(sum(pepe))
print(min(pepe))
print(np.argmin(pepe))
print(np.argmax(pepe))
print(np.mean(pepe))
print(la.norm(pepe))

import numpy as np
import numpy.linalg as la
pepe = np.linspace(3,7,5)
print(pepe)

import numpy as np
import numpy.linalg as la
pepe = np.arange(3,8)
print(pepe)

import numpy as np
import numpy.linalg as la
pepe = np.linspace(2,4,21)
print(pepe)

import numpy as np
import numpy.linalg as la
pepe = np.arange(2,4.1,0.1)
print(pepe)

x = np.array([2,4,6])
y = np.array([3,4,5])
print(x+y)
print(3*x-2*y)
print(x@y)
z = 2*x*y+3*x
print(z)

import math
import numpy as np
import numpy.linalg as la
pepe = np.arange(0,5)
fuckpepe = (pepe*math.pi)/2
print(fuckpepe)

import numpy as np

C = np.array([[1, 2], [3, 4]])
D = np.array([[5, 0], [0, 5]])

# Leggjum neðri línu D við efri línu C
new_C = np.vstack((C[0], D[1]))

print(new_C)

import numpy as np

M = np.zeros((10, 10), dtype=int)  # Búum til 10x10 heiltölu-núllfylki

for i in range(10):
    for j in range(10):
        M[i, j] = (i + 1) * (j + 1)

print(M)