# -*- coding: utf-8 -*-
"""F4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IOexclipc35W-4_dPRYwr9iJ2sTX6OPn

Fyrirlestur 4

***

KAFLI 8.2.5 Æfing: Prófnúmer og einkunnir
***
"""

#a)
from urllib.request import urlopen

f = urlopen("https://cs.hi.is/python/profnumer.txt")
tafla = {}
for lína in f:
    (nafn,hæð) = lína.decode().split()
    tafla[nafn] = hæð

for (nafn,hæð) in tafla.items():
   print(f"{nafn} {hæð}")

#b)
t = ['0176', '0542', '0970', '1419', '1577', '2785', '4218', '4854', '5469',         '6324', '6558', '7923', '8003', '8148', '8492', '9058', '9134']

n = ['Kjartan', 'Aðalheiður', 'Sigrún', 'Erla', 'Hulda', 'Bjarki', 'Kristín',           'Anton', 'Íris', 'Ívar', 'Ágúst', 'Steinunn', 'Eydís', 'Signý', 'Andri',           'Elías', 'Birta']

tafla = dict(zip(t, n))

for (t, n) in tafla.items():
    print(f"{t} {n}")

#C)
t = ['176', '542', '1577', '2785', '4218', '6354', '8003', '9134']
e = [8.5, 10.0, 4.5, 9.0, 7.5, 6.0, 8.5, 8.0]

tafla = {'0176': 'Kjartan', '0542': 'Aðalheiður', '0970': 'Sigrún', '1419': 'Erla', '1577': 'Hulda',
         '2785': 'Bjarki', '4218': 'Kristín', '4854': 'Anton', '5469': 'Íris', '6324': 'Ívar',
         '6558': 'Ágúst', '7923': 'Steinunn', '8003': 'Eydís', '8148': 'Signý', '8492': 'Andri',
         '9058': 'Elías', '9134': 'Birta'}

einkunnalisti = []
for t, e in zip(t, e):
    name = tafla.get(t.zfill(4), "error")
    einkunnalisti.append((name, t, e))

for student in einkunnalisti:
    print(f"{student[0]} {student[1]} {student[2]}")

"""KAFLI 8.3.3 Æfing: Verð mjólkurlítra"""

import csv
línur = ["Nýmjólk, 177", "Léttmjólk, 179", "Fjörmjólk, 219"]

verð = []
rdr = csv.reader(línur, skipinitialspace=True)
for row in rdr:
    vara, verd = row
    verð.append([vara, int(verd)])

print("| vara         | verd  |")
print("|-----------------|-------|")
for vara, verd in verð:
    print(f"| {vara:16} | {verd:5}  |")

"""KAFLI 8.4
***

Sýnidæmi: Skráaskrift með write
"""

with open("xy.dat", "w") as f:
   (x,y) = (3,4)
   f.write("x = {x}\n")
   f.write("y = {y}\n")

"""Sýnidæmi: Skráaskrift með print
***
"""

with open("xy1.dat", "w") as f:
  (x,y) = (6,7)
  print(f"x = {x}", file=f)
  print(f"y = {y}", file=f)

"""KAFLI 9
***

Æfing: Afritið skipanirnar að ofan inn í vinnubók og keyrið. Prófið að breyta:

***
"""

# Frumstilling teikningar
import matplotlib.pyplot as plt
plt.rc('axes', axisbelow=True)
plt.rc('figure', figsize=(8,4)) # (6,4) er sjálfgefið
plt.rc('savefig',bbox='tight')  # laga galla á savefig
from math import sqrt
x = list(range(6))
y = [sqrt(xi) for xi in x]
plt.figure(figsize=(7,3))
plt.scatter(x,y,s=50)
plt.plot(x,y)
plt.grid(True)

import matplotlib.pyplot as plt
plt.rc('axes', axisbelow=True)
plt.rc('figure', figsize=(8, 4))
plt.rc('savefig', bbox='tight')
from math import sqrt

x = list(range(10))
y = [sqrt(xi) for xi in x]

plt.figure(figsize=(10, 5))

plt.scatter(x, y, s=100)
plt.plot(x, y)

plt.grid(False)

"""9.2.3  Súlurit
***
"""

import matplotlib.pyplot as plt
from random import gauss

# fjölga
x = [gauss(0, 1) for i in range(1000)]
plt.hist(x, bins=12, range=(-3, 3))
plt.xlabel('x')
plt.ylabel('fjöldi gilda á hverju bili (af 1000)')
plt.show()

# fækka
x = [gauss(0, 1) for i in range(100)]
plt.hist(x, bins=12, range=(-3, 3))
plt.xlabel('x')
plt.ylabel('fjöldi gilda á hverju bili (af 100)')
plt.show()

# 6 súlur
x = [gauss(0,1) for i in range(500)]
plt.hist(x, bins=6, range=(-3,3))
plt.xlabel('x')
plt.ylabel('fjöldi gilda á hverju bili (af 500)')
plt.show()

"""KAFLI 9.3.2 Æfing: Súlurit af einkunnum
***
"""

import matplotlib.pyplot as plt
import requests

url = 'https://cs.hi.is/python/einkunn.txt'
response = requests.get(url)
grades = []

for line in response.text.strip().split("\n"):
    grade = float(line.split()[1])
    grades.append(grade)

plt.hist(grades, bins=10, range=(0, 10))
plt.xlabel('einkunnir')
plt.ylabel('fjöldi')
plt.title('Einkunnir')
plt.show()

"""KAFLI 9.5.1
***
"""

from math import sqrt
x = range(5)
y = [sqrt(t) for t in x]
plt.figure(figsize=(4, 1.8), dpi=90) # dpi=72 sjálfgefið
plt.plot(x, y, lw=3, ls=':', c='r', marker='o', ms=8)
plt.xlabel('x')
plt.ylabel('y = √x')

from math import sqrt
import matplotlib.pyplot as plt

x = range(5)
y = [sqrt(t) for t in x]
plt.figure(figsize=(4, 1.8), dpi=120)
plt.plot(x, y, lw=3, ls='-', c='b', marker='x', ms=12)
plt.xlabel('x')
plt.ylabel('y = √x')
plt.show()

"""9.5.2  Dæmi um legend
***

Æfing:  Prófið svo að bæta við cos(x) með tilheyrandi label

---


***
"""

from math import pi, sin, cos
from random import random
t = [k*2*pi/20 for k in range(21)]
s = [sin(x) for x in t]
c = [cos(x) for x in t]
y = [random() for k in range(21)]
plt.figure(figsize=(5,2))
plt.plot(t, s, label='sin(x)')
plt.plot(t, c, label='cos(x)')
plt.plot(t, y, label='slembitölur')
plt.grid(True)
plt.legend();

"""Prófið líka að fjölga punktunum (það þarf að breyta bæði 20 og 21 í stærri tölur).
***
"""

from math import pi, sin, cos
from random import random
t = [k*2*pi/200 for k in range(201)]
s = [sin(x) for x in t]
c = [cos(x) for x in t]
y = [random() for k in range(201)]
plt.figure(figsize=(5,2))
plt.plot(t, s, label='sin(x)')
plt.plot(t, c, label='cos(x)')
plt.plot(t, y, label='slembitölur')
plt.grid(True)
plt.legend();

"""KAFLI 9.5.3
***

Æfing: Súlurit
***
"""

from random import gauss

x = [gauss(0,1) for i in range(5000)]

plt.figure(figsize = (6,3))
plt.hist(x, bins=25, range=(-3,3), rwidth=0.8, color='pink', ec='k');
plt.xlabel('x-gildi');
plt.ylabel('fjöldi');
plt.grid(True, axis='y')

"""KAFLI 9.6.4
***

X SIN X
"""

import numpy as np
import matplotlib.pyplot as plt

(a,b) = (-5, 2)
x = np.linspace(a,b)
plt.figure(figsize=(9,6))
plt.grid(True)
plt.axvline(color='k')
plt.axhline(color='k')
plt.box(False)
plt.plot(x, x * np.sin(x))
plt.xlim([a,b])
plt.tick_params(length=0)
plt.show()

"""𝑒−2𝑥+1
***
"""

from numpy import linspace
import matplotlib.pyplot as plt

(a,b) = (-5,2)
x = linspace(a,b)
plt.figure(figsize=(9,6))
plt.grid(True)
plt.axvline(c='k')
plt.axhline(c='k')
plt.box(False)
plt.plot(x, [np.exp(-2 * t + 1) for t in x])
plt.xlim([a,b])
plt.tick_params(length=0)
plt.show()