# -*- coding: utf-8 -*-
"""F5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gu1Tfsl2h66iPvs80WAQbrUYREhNOyDA

Æfing: Fyrsta NumPy-æfingin
***

10.2.1  Vigur gefið gildi
***
"""

import numpy as np

x = np.array([1, 2, 3, 4, 6])
y = x.copy()
b = np.zeros((3))

print("np.array: ", x)
print("x.copy: ", y)
print("np.zeros:", b)

"""10.2.2  Einstök stök og hlutvigrar
***
"""

import numpy as np

x = np.array([1, 2, 3, 4, 6])

print("x[2]: ", x[2])
print("x[2:]: ", x[2:])
print("x[::2]: ", x[::2])

"""10.2.5  Aðferðir í stað falla
***

Æfing: Nokkur NumPy föll
***
"""

import numpy as np
import numpy.linalg as la

x = np.array([2, 3, 5, 7, 11])
print("vigur x: ", x)

print("Lengd x: ", len(x))
print("Summa x: ", sum(x))
print("Lágmarksgildi x: ", min(x))
print("Stærsta gildi x: ", max(x))
print("Index lagmarksgildi x: ", np.argmin(x))
print("Index hámarksgildi x: ", np.argmax(x))
print("meðaltal x: ", np.mean(x))
print("L2 norm af x: ", la.norm(x))

"""Æfing: Vigratilbúningur

***
"""

import numpy as np

linspaced = np.linspace(3, 7, 5)
aranged = np.arange(3, 8, 1)

print("linspaced: ", linspaced)
print("aranged: ", aranged)

import numpy as np

linspaced = np.linspace(2, 4, 20)
aranged = np.arange(2, 4.1, 0.1)

print("Vector using linspace: ", linspaced)
print("Vector using arange: ", aranged)

"""Æfing: Vigurreikningar
***
"""

import numpy as np

x = np.array([2, 4, 6])
y = np.array([3, 4, 5])

# x + y
sum_xy = x + y
print("x + y: ", sum_xy)

# 3x - 2y
three_x_minus_two_y = 3 * x - 2 * y
print("3x - 2y: ", three_x_minus_two_y)

# innfeldið x * y
integral_xy = np.dot(x, y)
print("Innfeldið x * y: ", integral_xy)

# vigurinn 𝑧 sem gefinn er með 𝑧𝑖=2𝑥𝑖𝑦𝑖+3𝑥𝑖
z = 2 * x * y + 3 * x
print("Vigurinn z: ", z)

"""Æfing: Stærðfræðiföll af vigrum
***
"""

import numpy as np

# Búið til vigurinn (0,𝜋/2,𝜋,3𝜋/2,2𝜋)..
angles = np.arange(0, 5) * np.pi / 2
print("Angles: ", angles)

# Reiknið svo sínus, kósínus og tangens
sine = np.sin(angles)
cosine = np.cos(angles)
tangent = np.tan(angles)

print("Sin: ", sine)
print("Cos: ", cosine)
print("Tan: ", tangent)

"""Æfing: Rökvigrar
***
"""

import matplotlib.pyplot as plt
x = np.array([0,14,15,16,15,13])
y = np.array([5,8,7,0,2,4])
I = x != 0
J = y != 0
K = I & J
plt.figure(figsize=(3,2))
plt.scatter(x[K], y[K])

"""Æfing: Margföldunartafla
***
"""

Z = np.zeros ((2,2))
C = np.array([[1,2], [3,4]])
D = np.array ([[5,0],[0,5]])

print(Z)
print(C)
print(D)

C[0,:] += D[1,:]
print(C)

np.set_printoptions(suppress=True, floatmode="fixed", precision=0)
M = np.zeros((10,10), int)
for i in range(10):
  for j in range(10):
    M[i,j] = (i+1)*(j+1)
M

"""Æfing: Bylting og afpökkun
***
"""

M = np.array([[1,4],[2,5], [3,6]])
print(M.T)
(u,v) =M.T
u,v

"""Æfing: loadtxt
***
"""

skrá = 'https://cs.hi.is/python/hiti-urkoma.txt'
(ár, hiti, úrkoma) = np.loadtxt(skrá).T
ár
hiti
plt.figure(figsize=(15,4))
plt.plot(ár,úrkoma)
plt.grid()
plt.show()

skrá = 'https://cs.hi.is/python/malmar.txt'
(eðlisþ, bræðslum) = np.loadtxt(skrá, usecols=(1,2), skiprows=1).T
plt.scatter(eðlisþ, bræðslum)