# -*- coding: utf-8 -*-
"""F7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SlkvRjbfTdv-8WDnjYk9J30idg9hJW4X

f7 Dæmi:
***

kafla 12.2.3. Tilraunir með hámarksflæði
***
"""

#b
import numpy as np, scipy.sparse as ssp
B = ssp.csr_matrix([[0,3,2,0],[0,0,1,3],[0,0,0,2],[0,0,0,0]])
flow = ssp.csgraph.maximum_flow(B, source=0, sink=3)
res = flow.residual.todense()
X = np.where(res > 0, res, 0)
print(f"Hamarkflaedi = {flow.flow_value}")
print("Tilsvarandi net:")
print(X)
#C
print("fow.residual:")
print(flow.residual)
print("res:")
print(res)