# -*- coding: utf-8 -*-
"""F8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yVsa_snCg31bIWrTdTXUXudFPVJJZ5QV

Fyrirlestur 8
***

13.1
***
"""

from random import randint

def draw():
    sort = ['hjarta', 'spaða', 'tígul', 'laufa']
    nafn = ['ás', 'tvistur', 'þristur', 'fjarki', 'fimma', 'sexa',
            'sjöa', 'átta', 'nía', 'tía', 'gosi', 'drottning', 'kóngur']
    litur = randint(0, 3)
    gildi = randint(0, 12)
    spil = sort[litur] + " " + nafn[gildi]
    return spil

# Test
print(draw())
print(draw())
print(draw())

#1)
hand = []

# Draga 5 spil
for i in range(5):
    hand.append(draw())

# Print hendina
print("Spil á hendi:")
for card in hand:
    print(card)

#2) (ekki alveg að ná þessum liði)
def has_two_deuces(hand):
    count = 0
    for card in hand:
        if "tveir" in card:
            count += 1

    return count == 2
num_hands = 100000
num_two_deuces = 0
for i in range(num_hands):
    hand = [draw() for j in range(5)]
    if has_two_deuces(hand):
        num_two_deuces += 1

probability = num_two_deuces / num_hands

print(f"Likur að fa tvær tvennur: {probability:.4f}")

"""13.3
***
"""

import numpy as np

rng = np.random.default_rng()
np.set_printoptions(suppress=True, precision=3, floatmode="fixed")

#1) 4×4 fylki með tölum úr stöðluðu normaldreifingunni, N(0,1)
mat = rng.normal(0, 1, size=(4, 4))
print(mat)

#2) vigur með 7 tölum í {2,4,6,…,100}
vec = rng.integers(1, 51, size=7) * 2
print(vec)

#3) 3×3 fylki með tölum á bilinu [2,5] með rng.random
arr = rng.random(size=(3, 3)) * 3 + 2
print(arr)

#4) fylki með tölum á bilinu [2,5] með rng.uniform
unif = rng.uniform(2, 5, size=10)
print(unif)

""" 13.4
 ***
"""

from random import randint, seed

x = [randint(1, 3) for i in range(5)]
print(x)

from random import randint, seed

seed(12345)

x = [randint(1, 3) for i in range(5)]
print(x)

"""13.5
***
"""

#1)
from random import shuffle

names = ["Ari", "Ása", "Jói", "Oli", "Una"]
shuffle(names)
print(names)

#2)
from random import sample

names = ["Ari", "Ása", "Jói", "Oli", "Una"]
chosen_names = sample(names, 3)
print(chosen_names)

#3)
from random import shuffle

x = [k + k**2 for k in range(1, 6)]
shuffle(x)
print(x)

#4)
from random import sample

spurning = ["Litur himinsins?", "2+2?", "Hver vann?", "Er sól?"]
svar = ["blár", "4", "Jói", "nei"]

indices = list(range(len(spurning)))

shuffled_indices = sample(indices, len(indices))

shuffled_spurning = [spurning[i] for i in shuffled_indices]
shuffled_svar = [svar[i] for i in shuffled_indices]

print(shuffled_spurning)
print(shuffled_svar)