# -*- coding: utf-8 -*-
"""f9.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OLu7NejCO2vXnun8jpJl6w1r8sxc812R
"""

def bilalisti2(T1,T2,clown):
  pepe= []
  for (nr,eigandi) in T1.items():
    if eigandi == clown:
      if nr in T2:
        pepe.append(T2[nr])
      else:
        pepe.append("ukjent model")
  return pepe
T1 = {"MSS-42": "Elín", "ZH-474": "Kristján", "JVD-69": "Kristján"}
T2 = {"MSS-42": "Hyundai", "ZH-474": "Toyota"}
print(bilalisti2(T1, T2, "Jón"))
print(bilalisti2(T1, T2,"Kristján"))



def sameining(T1,T2):
  sameina = set(T1.keys() | T2.keys())
  for nr in sameina:
    if nr
T1 = {"MSS-42": "Elín", "ZH-474": "Kristján", "JVD-69": "Kristján"}
T2 = {"MSS-42": "Hyundai", "ZH-474": "Toyota", "JVD-69": "Volvo"}

def sameiningg(T1, T2):
  T={}
  for (nr, eigandi) in T1.items():
    tegund = T2[nr]
    T[nr]= tegund + " sem " + eigandi + " á"
  return T
T1 = {"MSS-42": "Elín", "ZH-474": "Kristján", "JVD-69": "Kristján"}
T2 = {"MSS-42": "Hyundai", "ZH-474": "Toyota", "JVD-69": "Volvo"}
print(sameiningg(T1, T2))

def sameinalista(T1,T2):
  pepe = {}
  sameinafall = set(T1.keys() | T2.keys())
  for nr in sameinafall:
    s = T2.get(nr, " óþekkt tegund")
    if nr in T1:
      s+=" sem " + T1[nr] + " á "
    else:
      s+= " með óþekktan eiganda "
    pepe[nr] = s
  return pepe

T1 = {"MSS-42": "Elín", "ZH-474": "Kristján", "JVD-69": "Kristján", "XYZ-12": "Ari"}
T2 = {"MSS-42": "Hyundai", "ZH-474": "Toyota", "JVD-69": "Volvo", "AB-123": "Fiat"}
sameinalista(T1, T2)

import numpy as np
import numpy.linalg as la
u = np.array([5,2])
v = np.array([1,3])
A = np.array([[2,3], [4,5]])
B = np.array([[-4,3], [0,1]])



# 2u + 3v
print(2*u + 3*v)

#ii)
print(A@B.T@A@v + la.matrix_power(A + B,-1) @ (u + v))

#iii)
print(la.det(B) + u@v - v@(A*A*A*A*A @ u))

import numpy as np, numpy.linalg as la
A = np.array([
    [2, -3, 1],
    [1,1,0],
    [1,0,-2]
])
B = np.array([-1,-1,7])
x = la.solve(A,B)
print(x)

def skipti(L1,L2):
  pepe= []
  for i in range(len(L1)):
    pepe.append(L1[i])
    pepe.append(L2[i])
  return pepe

print(skipti([1, 3, 7], [2, 6, 8]))

def mislangir(L1,L2):
  pepe= []
  for i in range(max(len(L1),len(L2))):
    if i < len(L1):
      pepe.append(L1[i])
    if i < len(L2):
      pepe.append(L2[i])
  return pepe



print(mislangir([1, 3, 7, 9], [2, 6]) )

from re import T
def finnabíla(T1, T2, clown):
  pepe = []
  for (nr, tegund) in T2.items():
    if T1[nr] == clown:
      pepe.append(tegund)
  return pepe




T1 = {"MSS-42": "Elín", "ZH-474": "Kristján", "JVD-69": "Kristján"}
T2 = {"MSS-42": "Hyundai", "ZH-474": "Toyota", "JVD-69": "Volvo"}
print(finnabíla(T1, T2, "Kristján"))

def bilalisti(T1, T2, clown):
  pepe = []
  for (nr,tegund) in T1.items():
    if clown == tegund:
      if nr in T2:
        pepe.append(T2[nr])
      else:
        pepe.append("oþekkt tegund")
  return pepe

T1 = {"MSS-42": "Elín", "ZH-474": "Kristján", "JVD-69": "Kristján"}
T2 = {"MSS-42": "Hyundai", "ZH-474": "Toyota"}
print(bilalisti(T1, T2,"Kristján"))

def listi(T1,T2):
  pepe = {}
  for (nr, eigandi) in T1.items():
    pepe[nr]= T2[nr]+ " sem " + eigandi + " á"
  return pepe


T1 = {"MSS-42": "Elín", "ZH-474": "Kristján", "JVD-69": "Kristján"}
T2 = {"MSS-42": "Hyundai", "ZH-474": "Toyota", "JVD-69": "Volvo"}
print(listi(T1,T2))

def list(T1,T2):
  pepe= {}
  saman = set(T1.keys()|T2.keys())
  for nr in saman:
    s = T2.get(nr, "óþekkt")
    if nr in T1:
      s+= " SEM " + T1[nr] + "á "
    else:
      s+= "með óþekktan eiganda"
    pepe[nr] = s
  return pepe




T1 = {"MSS-42": "Elín", "ZH-474": "Kristján", "JVD-69": "Kristján", "XYZ-12": "Ari"}
T2 = {"MSS-42": "Hyundai", "ZH-474": "Toyota", "JVD-69": "Volvo", "AB-123": "Fiat"}
print(list(T1,T2))