# -*- coding: utf-8 -*-
"""Kafli1-4.5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k773X1fS7pyYXs7C_C3N4t-A5DtojKjd

# Kaflar 1–4.5
***
"""

import math
m=2
k1=3
k2=4
sveifla = 2*math.pi*(math.sqrt(m/k1+k2))
print(sveifla)

"""# Æfing: Ólögleg breytunöfn

1)
1. ólöglegt (má ekki byrja á tölu)
2. löglegt
3. ólöglegt (má ekki vera bandstrik)
4. löglegt
5. ólöglegt (def er "python reserved words")

2) Hvaða lykilorð í málinu byrja á a eða b?
and, as, assert, break

# Æfing: Útreikningur
"""

#1)
a=7/4
b=7//4
c=8/4
d=8//4
print(a,b,c,d)

#2)
a=7%4 #reikna rest
b=7**4 #7 í 4 veldi
print(a,b)

#3)
x=5
if 2 < x < 7 and x != 10:
  print("𝑥 er slétt tala minni en 8")

"""# Æfing: Breytum breytt"""

#1)
x=5
p = x == 5
q = x == 6
print(p,q)

#2)
#1)
x=5
x+=2
p = x == 5
q = x == 6
print(p,q)

#3)
x=5
y=10
(x,y)
p = x == 5
q = x == 6
print(p,q)

"""# Æfing: input og print"""

#1)
  s = input('Sláðu inn tölu: ')
  t = int(s)
  print(t)

#2)
x = 2
s = "AB"
print(x, s,sep=",",end=";")
print(x*2, s*2, sep=",")

# COLLATZ ÆFING
def næsta(x):
    # skilar næstu tölu á eftir x í Collatz-runu
    if x % 2 == 0:
        f = x//2
    else:
        f = 3*x + 1
    return f

def collatz_runa(n):
    # finnur og skrifar út Collatz-runu sem byrjar á n
    print('runa: ', end='')
    while n > 1:
        print(n, end=', ')
        n = næsta(n)
    print(n)

# Forrit sem prentar út Collatz-runur sem byrja á 2, 3,...,7:
print('Nokkrar Collatz-runur')
for n0 in range(2,8):
    collatz_runa(n0)