# -*- coding: utf-8 -*-
"""S1(V3)_3.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j3NeSkivuNTxsgjn-2_c2p3Z9Dku2aBo

# A. Hitastigum breytt
"""

# Celsius --> Farenheit


def celsius_to_fahrenheit(celsius):
    return (celsius * 9/5) + 32

def fahrenheit_to_celsius(fahrenheit):
    return (fahrenheit - 32) * 5/9

print("Celsius\tFahrenheit")
print("--------------------")
for i in range(-30, 55):
    if(i%5==0):
        celsius = i
        fahrenheit = celsius_to_fahrenheit(celsius)
        print(f"{celsius}\t\t{fahrenheit}")

"""# B. Rætur, lograr, kvaðröt"""

# FOR LOOP
import math

for tala in range(1, 11):
    print("Kvaðratrót af", tala, ": {:.2f}".format(math.sqrt(tala)))
    print("náttúrulegur logri", tala, ": {:.2f}".format(math.log(tala)))
    print("annað veldi", tala, ":", tala ** 2)
    print(" ")

#WHILE LOOP
import math

tala = 1
while tala <= 10:
    print("Kvaðratrót af", tala, ": {:.2f}".format(math.sqrt(tala)))
    print("náttúrulegur logri", tala, ": {:.2f}".format(math.log(tala)))
    print("annað veldi", tala, ":", tala ** 2)
    tala += 1
    print(" ")

"""# C. Lograr og veldi"""

# ln(1)
import math

ln_of_1 = math.log(1)
print(ln_of_1)

# ln exp(3)
import math

exp_3 = math.exp(3)
ln_exp_3 = math.log(exp_3)
print(ln_exp_3)

# log10 1000
import math
result = math.log10(1000)
print(result)

# log2 8
import math
result = math.log2(8)
print(result)

"""# D. Rúmmál kúlu"""

#1)
import math
radius = float(input("radius: " ))
volume = (4/3) * math.pi * math.pow(radius,3)
print(volume)

#2)
import math

def radius_from_ummál(ummál):
    radius = ummál / (2 * math.pi)
    return radius

ummál = float(input("ummál:"))
radius = radius_from_ummál(ummál)
print(radius)

#3)
def reikna_thyngd(edlismassi, volume):
    thyngd = edlismassi * volume
    return thyngd

edlismassi_gull = 19.3
hlid_lengd = 20
volume = (hlid_lengd)**3
thyngd = reikna_thyngd(edlismassi_gull, volume)

print("Þyngd gullteningsins er {} kg".format(thyngd/1000))

#4)
import math

ummal = 40000
diameter = ummal / math.pi
radius = diameter / 2

edlisthyngd = 5.5
volume = (4/3) * math.pi * (radius * 1000)**3
thyngd = edlisthyngd * volume
mass = thyngd / (1000 ** 3)

print("Massi jarðar {:.2f} ton".format(mass))

"""# E. Taflborð"""

#a
n=8
band= "-"
line = band*(2*n+1)
print("+" + line + "+")

#b
for n in range(9):
    if(n!=0 and n%2==0):
        print("X", end=" ")
    else:
        print(" ", end=" ")

board = []

for i in range(9):
    row = []
    for j in range(9):
        if i == 0 or i == 8:
            if j == 0:
                row.append("+")
            elif j == 8:
                row.append("+")
            else:
                row.append("--")
        elif j == 0 or j == 8:
            if i % 2 == 0:
                row.append(" |")
            elif j==8 and i!=0:
                row.append("|")
        else:
            if i % 2 == 0:
                row.append("   " if j % 2 == 0 else "X")
            else:
                row.append("X" if j % 2 == 0 else "   ")
    board.append(row)

for row in board:
    print("".join(row))