# -*- coding: utf-8 -*-
"""S10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19S24FkSJukSD-dIoWL3k7GZIh3O57y2x

S10 (38-CD, VV3, VV6-A)
***

C. Kennitölur og vartöluprófun

Skrifið fall sem ákvarðar hvort kennitala sem gefin er með 10 stafa streng (án bandstriks) sé með rétta vartölu og skilar svarinu sem rökgildi (True eða False). Prófið með "9999999999" og líka með eigin kennitölu.
***
"""

def has_valid_serial_number(ssn):
    # kikjum ef input er 10 tala strengur
    if len(ssn) != 10 or not ssn.isdigit():
        return False

    # reiknum út vartöluna
    serial = sum([int(ssn[i]) * [3, 2, 7, 6, 5, 4, 3, 2][i] for i in range(8)])
    serial = 11 - (serial % 11) if serial % 11 != 0 else 0

    return serial == int(ssn[9])
print(has_valid_serial_number("9999999999"))    # False
print(has_valid_serial_number("0402013748"))    # True

"""Í skránni https://cs.hi.is/python/kennitolur.txt eru skáldaðar upplýsingar um 15 próftaka, prófnúmer, kennitölur og nöfn. Lesið skrána inn í þrjá lista með því að nota np.loadtxt(...) og birtið töflu með innihaldinu.
***
"""

import numpy as np

url = "https://cs.hi.is/python/kennitolur.txt"
names, exam_numbers, ssn = np.loadtxt(url, delimiter=",", dtype=str, unpack=True)

import pandas as pd

df = pd.DataFrame({
    "Nafn": names,
    "Prófnúmer": exam_numbers,
    "Kennitala": ssn
})
print(df)

"""Vartöluprófið kennitölurnar (í for-lykkju). Ein þeirra stenst ekki prófun. Hvaða nemandi á hana?
***
"""

import urllib.request

def has_valid_serial_number(ssn):
    if len(ssn) != 10 or not ssn.isdigit():
        return False

    serial = sum([int(ssn[i]) * [3, 2, 7, 6, 5, 4, 3, 2][i] for i in range(8)])
    serial = 11 - (serial % 11) if serial % 11 != 0 else 0

    return serial == int(ssn[9])

url = "https://cs.hi.is/python/kennitolur.txt"

response = urllib.request.urlopen(url)
data = response.read().decode()

lines = data.strip().split("\n")

for line in lines:
    name, exam_number, ssn = line.strip().split(",")
    if not has_valid_serial_number(ssn):
        print("Nemandi sem stenst ekki prófun er:", name)
        break

"""Skrifið fall sem tekur við kennitölu og skilar tilsvarandi fæðingardegi með sniði: „17. ágúst 1958“. Prófið með eigin kennitölu, og líka kennitölu einhvers í skránni sem fæddur er á annari öld.
***
"""

import datetime

def get_dob_from_ssn(ssn):
    day = int(ssn[:2])
    month = int(ssn[2:4])
    year = int(ssn[4:6])
    if year >= 36:
        year += 1900
    else:
        year += 2000
    dob = datetime.date(year, month, day)
    return dob.strftime("%d. %B %Y")
print(get_dob_from_ssn("0301012520"))
print(get_dob_from_ssn("2605973109"))

"""D. Uppflettitöflur
Lesið skrána sem notuðu var í dæmi C inn í þrjá lista eins og gert var þar.

Búið til uppflettitöflu (dictionary) til að fletta upp á prófnúmeri út frá nafni (nafn er lykill og prófnúmer er gildi).
***
"""

import urllib.request

url = "https://cs.hi.is/python/kennitolur.txt"
data = urllib.request.urlopen(url)

exam_numbers = {}

for line in data:
    line = line.decode("utf-8").strip()
    name, exam_number, kennitala = line.split(",")
    exam_numbers[name] = exam_number

print(exam_numbers)

"""Skrifið forrit sem skrifar út lista (með haus) yfir nöfn og prófnúmer í íslenskri stafrófsröð.
***
"""

import numpy as np
import urllib.request

def íslenska(s):
   # notað sem 'key' í sort eða sorted til að raða í íslenska stafrófsröð,
   # t.d. print(sorted(['ár','bára','bali','akur'], key=íslenska))"""
   return [íslenska.k.get(c.lower(),0) for c in s]
íslenska.a = list('aábcdðeéfghiíjklmnoópqrstuúvwxyýzþæö')
íslenska.k = dict(zip(íslenska.a, range(1,len(íslenska.a)+1)))

url = "https://cs.hi.is/python/kennitolur.txt"
with urllib.request.urlopen(url) as f:
    data = np.loadtxt(f, dtype=str, delimiter=',', skiprows=1)

sorted_data = sorted(data, key=lambda x: islenska(x[0]))

print("Nafn\t\t\tProf Numer")
for name, number, _ in sorted_data:
    print(f"{name.ljust(25)}{number}")

"""Hér er listi yfir prímtölur númer 1 til 25:

***
"""

P = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]

nrp = {}
for i, prime in enumerate(P):
    nrp[prime] = i+1

def lookup(number, nrp):
    if number > 99:
        print(f"{number} er of stor")
    elif number in nrp:
        print(f"{number} er {nrp[number]} primtalan")
    else:
        print(f"{number} er ekki primtala")

lookup(13, nrp)
lookup(16, nrp)
lookup(103, nrp)

"""Verkefni úr Völdum efnum um stærðfræði og reiknifræði (https://cs.hi.is/strei Links to an external site.)

VV3 (Fall Rosenbrocks)
***

Skrifið fall rosen(x,y) til að reikna gildi fallsins. Prófið að reikna 𝑓(−1.2,1) sem ætti að gefa 24.2.
***
"""

def rosen(x, y):
    return (1 - x)**2 + 100*(y - x**2)**2
rosen(-1.2, 1)

"""Teiknið hæðarlínumynd af Rosenbrock-fallinu með plt.contour á svæðinu [−2,2]×[−1,3]. Látið hæðarlínurnar vera dökkbláar, merkið þær líkt og gert er í sýnidæminu Hæðarlínur falls í kafla A1, og hafið netlínur (grid) með. Til að fá góða mynd þarf bæði að reikna fallið á þéttu neti (t.d. 300×300) og velja hæðarlínugildin, sem fást með stikanum levels vel. Gildin 0.2,22,62,102,…,462 gefa t.d. ágæta mynd.
***
"""

import numpy as np
import matplotlib.pyplot as plt

def rosen(x, y):
    return (1 - x)**2 + 100*(y - x**2)**2

x = np.linspace(-2, 2, 300)
y = np.linspace(-1, 3, 300)

X, Y = np.meshgrid(x, y)

Z = rosen(X, Y)

levels = np.append([0.2], np.arange(2,50,4)**2)

plt.contour(X, Y, Z, levels=levels, colors='navy')

plt.grid()
plt.xlabel('x')
plt.ylabel('y')
plt.title("hæðarlínumynd af Rosenbrock-fallinu ")

plt.show()

"""VV6A (Stiglar og lágmörkun)
***

Ákvarðið stigul 𝑓(þ.e.a.s. ∇𝑓), skrifið Python-fall sem finnur hann og notið það til að reikna ∇𝑓(𝑝)
***
"""

def gf(x, y):
    return (2*x*y + 2*y**2 - 3*y, x**2 + 4*x*y - 3*x)
p = (1, 1)
gf(*p)

"""Lát 𝑢=(−1,−1). Notið Python-fallið úr a-lið líka til að reikna stefnuafleiðu 𝑓 í stefnu 𝑢 í punktinum 𝑝. Búið líka til einhvern punkt og vigur úr afmælisdegi ykkar og reiknið tilsvarandi stefnuafleiðu.
***
"""

import numpy as np

def f(x, y):
    return x**2*y + 2*x*y**2 - 3*x*y + 4

p = (1, 1)

u = np.array([-1, -1]) / np.sqrt(2)

dfdu = np.dot(gf(*p), u)

print("Stefnuafleiða f í stefnu u í punktinum p:", dfdu)

"""ég á afmæli 3. jan
***
"""

p = (1, 3)
v = np.array([1, -1])

vhat = v / np.linalg.norm(v)

dfdv = np.dot(gf(*p), vhat)

print("Stefnuafleiða f í stefnu p í punktinum v:", dfdv)

"""Teiknið að lokum hæðarlínur 𝑓 á svæðinu [0,3]×[0,2].
***
"""

import matplotlib.pyplot as plt
import numpy as np

def f(x, y):
    return x**2*y + 2*x*y**2 - 3*x*y + 4

x = np.linspace(0, 3, 300)
y = np.linspace(0, 2, 300)
X, Y = np.meshgrid(x, y)

Z = f(X, Y)

levels = np.linspace(0, 35, 50)
plt.contour(X, Y, Z, levels=levels, colors='blue')

plt.xlabel('x')
plt.ylabel('y')
plt.title('hæðarlínur f á svæðinu [0,3]×[0,2]')

plt.show()