# -*- coding: utf-8 -*-
"""s11.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fo7mHMZtnv2ng9qkCQYT1glj8SAg8WhK
"""

def celsius(k):
  return 9/5*k+32


print(" °C °F ")
print("----------")
for k in range(-30,51,5):
  print(f"{k:3}, {celsius(k):6}")

import math as math
print("sqrt    log.     veldi")
print("----------------------")
for i in range(1,11):
  kvad=math.sqrt(i)
  log=math.log(i)
  veldi=i**2
  print(f"{kvad:.2f}, {log:.2f}, {veldi:3}")

import math as math
print("sqrt    log.     veldi")
print("----------------------")
i=1
while i<11:
    kvad=math.sqrt(i)
    log=math.log(i)
    veldi=i**2
    print(f"{kvad:.2f}, {log:.2f}, {veldi:3}")
    i+=1

import math as math
x=math.log(1)
print(x)
y=math.log(math.exp(3))
print(y)
s=math.log10(1000)
print(s)
q=math.log2(8)
print(q)

def rk(r):
  return (4*math.pi*r**3)/3

r=2
print(rk(r))

import math as math
def radius(circumference):
  rad = (circumference)/(2*math.pi)
  return rad
print(round(radius(33.51),1))

def fyrned(n):
  print(f"+"+f"-"*(2*n+1)+f"+")
def secondline(n):
  print("|",end="")
  print(" x"*int(n/2),end="")
  print(" |")
def thirdline(n):
  print("| ",end="")
  print("x "*int(n/2),end="")
  print("|")
def taflbord(n):
  count = n
  if(n%2==0 and n>2):
    fyrned(n)

    while count>0:
      secondline(n)
      thirdline(n)
      count=count-2
      fyrned(n)
  else:
    print("error : input should be a even number more than 2")
taflbord(8)
taflbord(4)
taflbord(3)

from math import sin, e

def fall(f,a,b):
    sum = (b-a)*(f(a)+f(b))/2
    return sum

def g(x):
    return sin(x)/x

def h(x):
    return e**x

i1 = fall(g,1,2)
i2 = fall(h,0,1)

def trapis(f, a, b, n):
    s = 0.0
    dX = (b-a)/n
    s += f(a)/2.0
    for k in range(1,n):
        s += f(a+k*dX)
    s += f(b)/2.0
    return dX*s

def simpson(f,a,b,n):
    dX = (b-a)/n
    s = f(a) + f(b)
    for k in range(1, n, 2):
        s += 4*f(a+k*dX)
    for i in range (2, n-1, 2):
        s += 2*f(a+i*dX)
    return s*(dX/3)

print(f"Nálgunn (*) {simpson(g,1,2,4):.5f}")
print(f"Nálgunn (**) {simpson(h,5,3,2):.5f}")
print(f"7 aukastafi fyrir (**) þar sem n=20, {simpson(h,0,1,20):.8f}")
print(f"7 aukastafi fyrir (*) þar sem n=20, {simpson(g,1,2,20):.8f}")
print(f"Nálgunn fyrir afmælisdagur {simpson(g,8,19,97):.5f}")

def br(x):
  sorted = True
  while(sorted):
    sorted = False
    for i in range(1,len(x)):
      if x[i-1]> x[i]:
        temp = x[i-1]
        x[i-1]=x[i]
        x[i]=temp
        sorted=True



x=[3,8,1,2,5,4]
print("an unsorted list", x)
br(x)
print("sorted list", x)

def stik(u,p,k,m):
  return int((u*(1+(p/100))**k)*(1+(((p/100)*m)/12))-u)


p=2
u=10000
k=3
m=4
print(stik(u,p,k,m))

def telja(s):
  return [len(ord) for ord in s.split()]


print(telja("Afi minn og amma mín"))

def hropa(s):
  sup= s.upper()
  sup+="!!"
  print(sup)


hropa("Thor Sanchez")

def storir(s):
  return [ord[0].isupper() for ord in s.split()]

print(storir("Mario Balotelli doesnt celebrate"))

import math
def toldiff(f,a,h):
  return (((f(a+h))-(f(a-h)))/(2*h))
def f(x):
  return math.sqrt(x)


h=math.pow(10,(-4))
print(toldiff(f, 4, h))

isl_ens = {
"reipi": "rope",
"hús": "house",
"rauður":"red"
}

def snuavid(U):
  return{v: k for k, v in U.items()}

print(snuavid(isl_ens))

def shell(L):
    N=len(L)
    for k in range(0,N):
      bil= N//2**k
      if bil < 1:
        break
      for i in range(0,bil-1):
        L[i:N:bil] = innsetningar(L[i:N:bil])
    return L

from urllib.request import urlopen
import numpy as np
skrá = "https://cs.hi.is/python/ord.txt"
m = np.loadtxt(skrá, skiprows=1, dtype=str).T