# -*- coding: utf-8 -*-
"""s2.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vh9H88lMHtDMcY37LdfFJhRehPXoEhPk

Verkefni S2

V2B
"""

from math import sin

def f(x):
    if x == 0:
        return 0
    else:
        return sin(x)/x

def Simpsons(f,a,b,n):
    if n % 2 != 0:
      return None

    h = (b-a)/n
    first = f(a)
    last = f(b)

    x = a
    sum = 0
    for i in range(n-1):
        x += h
        value = f(x)
        if i % 2 == 0:
            sum +=4 * value
        else:
            sum += 2 * value

    total = (h/3)*(first+sum+last)
    return round(total, 4)

print(Simpsons(f,1,2,2))

"""V7"""

def bolurodun(x):
    n = len(x)
    vixlad = True
    while vixlad:
        vixlad = False
        for i in range(1, n):
            if x[i-1] > x[i]:
                x[i-1], x[i] = x[i], x[i-1]
                vixlad = True
    return x

# testum forritið
print(bolurodun([3, 8, 1, 2, 5, 4]))

""" V38B"""

def vextir(u, p, k, m):
    a = p / 100
    v = u * (1 + a) ** k * (1 + a * m / 12) - u
    return int(v)

# testum forritið
print(vextir(10000, 2, 3, 4)) # Output: 618

import datetime

now = datetime.datetime.now()
afmaeli = datetime.datetime(2001, 1, 4)

finna_mun = now - afmaeli
aldur_ar = finna_mun.days // 365
aldur_man = finna_mun.days % 365 // 30

def vextir(u, p, k, m):
    a = p / 100
    v = u * (1 + a) ** k * (1 + a * m / 12) - u
    vextir_percent = v / u * 100
    return f"Total vextir: {v} ISK, Vextir %: {vextir_percent} %"

# Test forrit
print(vextir(25000, 3, aldur_ar, aldur_man))

import math

def double_time(n):
    r = n/100/12
    t = math.log(2) / math.log(1 + r)
    years = int(t/12)
    months = int(t % 12)
    return f"It takes {years} years and {months} months to double the amount with {n}% interest"

# Test the function
print(double_time(13))