# -*- coding: utf-8 -*-
"""S3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bvawQ5EYD7_9bHjILWo4HbiKVazPbdcc

S3
***

V4 (Orðaleikur)
***
"""

#1)
def count(s):
    ord = s.split()
    telja = []
    for ord in ord:
        telja.append(len(ord))
    return telja
print(count("Afi minn og amma mín"))

#2)
def hropa(s):
    return s.upper() + "!!"

print(hropa("Thor"))

#3)
def large(s):
    ord = s.split()
    nidurstada = []
    for ord in ord:
        nidurstada.append(ord[0] == ord[0].upper())
    return nidurstada

print(large("Góðann Daginn"))

"""V10 (Töluleg diffrun)
***
"""

#1)
def töldiff(f, a, h):
    return (f(a + h) - f(a - h)) / (2 * h)

def f(x):
    return x**0.5

print(töldiff(f, 4, 10**-4))

"""ekki alveg að skilja dæmi 2 í V10:(

V11 (Uppflettitafla afturábak)
***
"""

#1)
def snúavið(U):
    return {v: k for k, v in U.items()}

isl_ens = {"reipi": "rope", "hús": "house", "rauður": "red"}
ens_isl = snúavið(isl_ens)

print(ens_isl)

#2)
def snúavið2(U):
    V = {}
    for g, v in U.items():
        if v in V:
            V[v].append(g)
        else:
            V[v] = [g]
    return V

isl_ens = {"reipi": "rope", "hús": "house", "rauður": "red", "tómarúm": "vaccum", "ryksuga": "vaccum"}
ens_isl = snúavið2(isl_ens)

print(ens_isl)