# -*- coding: utf-8 -*-
"""S4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gbWq7aL7z13XSzQ1WAUDgx8fLsb1Gl6F

S4↓
***

V12
***
"""

def shell_röðun(A):
    N = len(A)
    interval = N // 2
    while interval >= 1:
        for i in range(interval):
            for j in range(i, N, interval):
                k = j
                while k >= interval and A[k-interval] > A[k]:
                    A[k], A[k-interval] = A[k-interval], A[k]
                    k -= interval
        interval //= 2
    return A

print(shell_röðun([8,3,2]))
print(shell_röðun([8,5,1,9,6,2,1,7,11,3]))
print(shell_röðun([20, 33, 18, 17, 16, 43, 14, 13, 44, 11, 99, 7]))

"""V13
***
"""

#1)
from urllib.request import urlopen

f = urlopen("https://cs.hi.is/python/ord.txt")
words = []

for line in f:
   ord = line.decode().strip()
   words.append(ord)

print("Fyrstu 5 orðin:")
for i in range(5):
    print(words[i])

print("\nTíu þúsundasta hvert orð:")
for i in range(10000, len(words), 10000):
    print(words[i])

print("\nÖll orð sem eru lengri en 30 stafir:")
for ord in words:
    if len(ord) > 30:
        print(ord)

#2)
def spegilorð(s):
    return s == s[::-1]
from urllib.request import urlopen

f = urlopen("https://cs.hi.is/python/ord.txt")
words = []

for line in f:
    ord = line.decode().strip()
    words.append(ord)

palindromes = [ord for ord in words if spegilorð(ord)]

for i in range(0, len(palindromes), 10):
    print(" ".join(palindromes[i:i+10]))

#3)
from urllib.request import urlopen

def is_vowel(c):
    vowels = "aeiouAEIOU"
    return c in vowels

f = urlopen("https://cs.hi.is/python/ord.txt")
words = []

for line in f:
    ord = line.decode().strip()
    words.append(ord)

max_consonants = 0
result = []

for ord in words:
    vowels = sum(1 for c in ord if is_vowel(c))
    consonants = len(ord) - vowels
    if vowels == 1 and consonants > max_consonants:
        result = [ord]
        max_consonants = consonants

    elif vowels == 1 and consonants == max_consonants:
        result.append(ord)

print("Finnið þau orð í skránni sem hafa einn sérhljóða og hámarksfjölda samhljóða:")
print(" ".join(result))

"""V15
***
"""

#1)
import urllib.request

eink_tafla = {}
url = 'https://cs.hi.is/python/einkunn.txt'
response = urllib.request.urlopen(url)
for line in response:
    nr, grade = line.strip().decode().split(None, 1)
    eink_tafla[nr] = grade

nofn_table = {}
url = 'https://cs.hi.is/python/nofn.txt'
response = urllib.request.urlopen(url)
for line in response:
    nr, name = line.strip().decode().split(None, 1)
    nofn_table[nr] = name

result = {nofn_table[nr]: grade for nr, grade in eink_tafla.items()}

for name, grade in result.items():
    print(name, grade)

#2)
eink_tafla = {}
url = 'https://cs.hi.is/python/einkunn.txt'
response = urllib.request.urlopen(url)
for line in response:
    nr, grade = line.strip().decode().split(None, 1)
    eink_tafla[nr] = grade

nofn_tafla = {}
url = 'https://cs.hi.is/python/nofn.txt'
response = urllib.request.urlopen(url)
for line in response:
    nr, name = line.strip().decode().split(maxsplit=1)
    nofn_tafla[nr] = name

result = {nofn_tafla[nr]: grade for nr, grade in eink_tafla.items()}

for name, grade in result.items():
    print(name, "  ", grade)

import urllib.request

eink_tafla = {}
url = 'https://cs.hi.is/python/einkunn.txt'
response = urllib.request.urlopen(url)
for line in response:
    nr, eink = line.strip().decode().split(None, 1)
    eink_tafla[nr] = eink

nofn_tafla = {}
url = 'https://cs.hi.is/python/nofn.txt'
response = urllib.request.urlopen(url)
for line in response:
    nr, nafn = line.strip().decode().split(maxsplit=1)
    nofn_tafla[nr] = nafn

result = {nofn_table[nr]: eink for nr, eink in eink_tafla.items()}

print("Numer".ljust(12), "eink".ljust(8), "nafn")
for nr, eink in eink_tafla.items():
    nafn = nofn_tafla[nr]
    print(nr.ljust(12), eink.ljust(8), nafn)

highest_grade = 0
highest_grade_name = ""
for nafn, eink in result.items():
    if float(eink) > highest_grade:
        highest_grade = float(eink)
        highest_grade_name = nafn
print("Hæsta einkunn:", highest_grade)
print("Nafn:", highest_grade_name)