# -*- coding: utf-8 -*-
"""s6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AOt322RaaitKal1kkXrqNyMoc3XnAvqm

Verkefni 22: Sínussveiflur
***
"""

import numpy as np
import matplotlib.pyplot as plt


def f(x):
    return np.sin(x) + np.sin(2*x) - 2*np.sin(3*x)

x = np.linspace(-np.pi, 3*np.pi, 1000)

plt.plot(x, f(x))

plt.xlabel('x')
plt.ylabel('f(x)')
plt.title('f(x) = sin(x) + sin(2x) - 2sin(3x)')

for s in ['left','bottom']:
    plt.gca().spines[s].set_position('zero')

plt.show()

"""Verkefni 23: Málmavinnsla
***

Sætistölur eðallofttegunda
***
"""

def calculate_noble_gases(k):
    if k % 2 == 0:
        return ((k+1)*(k+2)*(k+3))//6 - k//2 + 1
    else:
        return ((k+1)*(k+2)*(k+3))//6 - (k-1)//2 - 2

for k in range(1, 8):
    print(f"k={k}: {calculate_noble_gases(k)}")

"""Lotur og flokkar
***
"""

def period_and_group(s):
    k = 1
    while calculate_noble_gases(k) < s:
        k += 1
    sk_minus_1 = calculate_noble_gases(k-1)
    sk = calculate_noble_gases(k)
    if s == 1:
        F = 1
    elif 1 < s <= sk_minus_1 + 2:
        F = s - sk_minus_1
    else:
        F = max(3, 18 + s - sk)
    if k in range(1, 3):
        group_num = F
    elif k in range(3, 11):
        group_num = 2
    else:
        group_num = F - 2
    return (k, group_num)


print("3:", period_and_group(3))
print("18:", period_and_group(18))
print("58:", period_and_group(58))
print("71:", period_and_group(71))

"""Íslensk og ensk málmanöfn
***
"""

import numpy as np
import urllib.request

url = "https://cs.hi.is/python/allir-malmar.txt"
data = np.genfromtxt(urllib.request.urlopen(url), dtype=None, delimiter=";", names=True, encoding="utf-8")

icelandic_to_english = dict(zip(data["Málmur"], data["Enska"]))

def íslenska(s):
    """Used as 'key' in sort or sorted to sort in Icelandic alphabetical order,
    e.g. print(sorted(['ár','bára','bali','akur'], key=íslenska))"""
    return [íslenska.k.get(c.lower(), 0) for c in s]

íslenska.a = list('0123456789aábcdðeéfghiíjklmnoópqrstuúvwxyýzþæö')
íslenska.k = dict(zip(íslenska.a, range(1, len(íslenska.a)+1)))

icelandic_names = sorted(data["Málmur"], key=íslenska)

for name in icelandic_names:
    print(f"{name}: {icelandic_to_english.get(name)}")

"""Eðlisþyngd eftir sæti
***
"""

import numpy as np
import matplotlib.pyplot as plt

data_url = 'https://cs.hi.is/python/allir-malmar.txt'
data = np.genfromtxt(data_url.encode(), delimiter=';', skip_header=1, usecols=(2, 3, 5), converters={3: lambda x: float(x.replace(',', '.'))})

period_colors = {
    1: 'red',
    2: 'green',
    3: 'blue',
    4: 'purple'
}

fig, ax = plt.subplots()
for i in range(1, 5):
    mask = data[:, 2] == i
    ax.scatter(data[mask, 0], data[mask, 1], color=period_colors[i], label=f"Period {i}")
ax.legend()
ax.set_xlabel("Hipparcos magnitude")
ax.set_ylabel("B-V color index")
plt.show()