# -*- coding: utf-8 -*-
"""S7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GR6z4bLhhLhmOJ4Yq9T3BBGQCsuoWRYP

25  Jafna bestu línu
***
"""

#2)
import numpy as np
import matplotlib.pyplot as plt
from urllib.request import urlopen

url = "http://cs.hi.is/python/hiti-urkoma.txt"
data = urlopen(url).readlines()
data = [line.decode('utf-8').strip().split() for line in data]
data = np.array(data, dtype=float)

temp = data[:, 1]
precip = data[:, 2]

a, b = np.polyfit(temp, precip, deg=1)
line = a * temp + b

plt.figure(figsize=(12,6))
plt.scatter(temp, precip, s=10)
plt.plot(temp, line, color='red')
plt.xlabel('Hitastig (Celsius)')
plt.ylabel('úrkoma (mm)')
plt.title('jafna bestu línu fyrir hita á x-ás og úrkomu á y-ás')
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from urllib.request import urlopen

url = "http://cs.hi.is/python/hiti-urkoma.txt"
data = urlopen(url).readlines()
data = [line.decode('utf-8').strip().split() for line in data]
data = np.array(data, dtype=float)

year = data[:, 0]
temp = data[:, 1]

line_coeffs = np.polyfit(year, temp, deg=1)
parabola_coeffs = np.polyfit(year, temp, deg=2)
line = np.polyval(line_coeffs, year)
parabola = np.polyval(parabola_coeffs, year)

plt.figure(figsize=(12,6))
plt.scatter(year, temp, s=10)
plt.plot(year, line, color='red', label='Besta lina')
plt.plot(year, parabola, color='green', label='Besta parabóla')
plt.xlabel('ár')
plt.ylabel('ársmeðalhiti (Celsius)')
plt.title('ársmeðal hiti síðustu ár ')
plt.legend()
plt.show()

"""28  Kínverskt jöfnuhneppi
***
"""

import numpy as np

# set up the system of equations
A = np.array([[1, 1], [1, -1]])
B = np.array([8, -4])

# solve for the unknowns
x = np.linalg.solve(A, B)

# display the results
num_buyers = int(x[0])
item_cost = int(x[1])
print("Hversu margir kaupa:", num_buyers)
print("Verd:", item_cost)

"""29  Fjarlægð milli borga
***
"""

#1)
import math


r1 = 6370  # radius af jörðinni
l1 = math.radians(90 - 64)  # lat í radius
b1 = math.radians(-22)  # long í radius

x1 = r1 * math.sin(l1) * math.cos(b1)
y1 = r1 * math.cos(l1) * math.cos(b1)
z1 = r1 * math.sin(b1)

r2 = 6370
l2 = math.radians(90 - 51.5)
b2 = math.radians(0)

x2 = r2 * math.sin(l2) * math.cos(b2)
y2 = r2 * math.cos(l2) * math.cos(b2)
z2 = r2 * math.sin(b2)

dot_product = x1*x2 + y1*y2 + z1*z2

magnitude_x = math.sqrt(x1**2 + y1**2 + z1**2)
magnitude_y = math.sqrt(x2**2 + y2**2 + z2**2)

angle = math.degrees(math.acos(dot_product / (magnitude_x * magnitude_y)))

print("Gráðan á milli Reykjavik og London:", angle, "gráður.")

#2)
import math

r1 = 6370
l1 = math.radians(64)
b1 = math.radians(-22)

r2 = 6370
l2 = math.radians(51.5)
b2 = math.radians(0)

delta_l = l2 - l1
delta_b = b2 - b1
a = math.sin(delta_l / 2)**2 + math.cos(l1) * math.cos(l2) * math.sin(delta_b / 2)**2
c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
d = r1 * c

print("lengd á milli Reykjavik og London er:", d, "km.")