# -*- coding: utf-8 -*-
"""s8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OosnboCD1WCc0H5lXeVhFkPCL8CuMnj-
"""

import urllib.request
import numpy as np
import matplotlib.pyplot as plt

#1)
url = 'http://cs.hi.is/python/karfa.txt'
filename = 'karfa.txt'
urllib.request.urlretrieve(url, filename)

data = np.loadtxt(filename)
age = data[:,0]
height = data[:,1]
weight = data[:,2]

fig, axs = plt.subplots(1, 3, figsize=(12, 4))

axs[0].hist(age, bins=np.arange(15, 50, 2), color='purple')
axs[0].set_xlabel('aldur (years)')
axs[0].set_ylabel('tíðni')
axs[0].set_title('aldur')

axs[1].hist(height, bins=np.arange(150, 220, 5), color='green')
axs[1].set_xlabel('hæð (cm)')
axs[1].set_ylabel('tíðni')
axs[1].set_title('hæð')

axs[2].hist(weight, bins=np.arange(50, 150, 5), color='blue')
axs[2].set_xlabel('þyngd (kg)')
axs[2].set_ylabel('tíðni')
axs[2].set_title('þyngd')

plt.tight_layout()
plt.show()

import numpy as np
import urllib.request
import matplotlib.pyplot as plt

#2)
url = 'http://cs.hi.is/python/karfa.txt'
filename = 'karfa.txt'
urllib.request.urlretrieve(url, filename)

data = np.loadtxt(filename)
height = data[:,1]
weight = data[:,2]

plt.scatter(height, weight, color='purple', alpha=0.5)
plt.xlabel('hæð (cm)')
plt.ylabel('þyngd (kg)')
plt.title('hæð vs þyngd')

m, b = np.polyfit(height, weight, 1)
plt.plot(height, m*height + b, color='red')

plt.show()

import numpy as np
import urllib.request
import matplotlib.pyplot as plt

#3)
url = 'http://cs.hi.is/python/karfa.txt'
filename = 'karfa.txt'
urllib.request.urlretrieve(url, filename)

data = np.loadtxt(filename)
height = data[:,1]
weight = data[:,2]


a, b, c = np.polyfit(height, weight, 2)

plt.scatter(height, weight, color='purple', alpha=0.5)
plt.xlabel('hæð (cm)')
plt.ylabel('þyngd (kg)')
plt.title('hæð vs þyngd')

x = np.linspace(height.min(), height.max(), 100)
y = a*x**2 + b*x + c
plt.plot(x, y, color='red')


plt.show()

import numpy as np
import urllib.request

#4)
url = 'http://cs.hi.is/python/karfa.txt'
filename = 'karfa.txt'
urllib.request.urlretrieve(url, filename)

data = np.loadtxt(filename)
age = data[:,0]
height = data[:,1]
weight = data[:,2]

median_age = np.median(age)
print("Miðtala: ", median_age)

idx_younger = age < median_age
idx_older = age >= median_age
height_younger = height[idx_younger]
height_older = height[idx_older]

avg_height_younger = np.mean(height_younger)
avg_height_older = np.mean(height_older)
print("meðalhæð yngri: ", avg_height_younger)
print("meðalhæð eldri: ", avg_height_older)

"""dæmi 34
***
"""

#1)
import urllib.request
import numpy as np


url = 'https://cs.hi.is/python/aldursdreifing.txt'


with urllib.request.urlopen(url) as f:
    data = f.read().decode('utf-8')


data = np.loadtxt(data.splitlines(), skiprows=1)


birth_rates = data[:, 3]
survival_rates = np.append(data[:, 2], 0)[:-1]


leslie_matrix = np.zeros((len(birth_rates), len(birth_rates)))
leslie_matrix[0,:] = birth_rates
leslie_matrix[1:, :-1] = np.eye(len(birth_rates) - 1)
leslie_matrix[:, -1] = survival_rates


population = np.array([364260] + [0]*(len(birth_rates)-1))

for year in range(2020, 2076, 5):
    population = leslie_matrix @ population
    print(year, int(population.sum()))