# -*- coding: utf-8 -*-
"""S9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O8O2jBFHJYDPLR7wihknvvlMNLGun9h_

Verkefni 35: Póker
***
"""

from random import sample

def pókerhönd():
  stokkur = [(i,j) for i in range(1,5) for j in range(1,14)]
  return sample(stokkur, 5)

def með_tvær_tvennur(hönd):
  # Skilar sönnu ef hönd geymir tvær tvennur
  gildi = [spil[1] for spil in hönd]
  M = set(gildi)                 # búa til mengi
  if len(M) != 3:
    return False                 # það verða að vera 3 gildi
  for spil in M:
    talning = gildi.count(spil)
    if talning > 2: return False # og ekkert spil má koma 3svar
  return True                    # það eru tvær tvennur!

def hlutfall_með_2x2(n):
  talning = 0
  for i in range(n):
    hönd = pókerhönd()
    if með_tvær_tvennur(hönd):
      talning += 1
  return talning/n

hf = hlutfall_með_2x2(100000)
print(f'Hlutfall með tvær tvennur: {hf*100:.1f}%')

#1)
def two_like_cards(hand):
    values = [card[1] for card in hand]
    for value in values:
        if values.count(value) == 2:
            return True
    return False

#2)
def three_like_cards(hand):
    values = [card[1] for card in hand]
    for value in values:
        if values.count(value) == 3:
            return True
    return False

#3)
def full_house(hand):
    values = [card[1] for card in hand]
    for value in values:
        if values.count(value) == 3:
            for other_value in values:
                if other_value != value and values.count(other_value) == 2:
                    return True
    return False

#4)
def color(hand):
    suits = [card[0] for card in hand]
    for suit in suits:
        if suits.count(suit) == 5:
            return True
    return False

import random

# Simulate hands
num_hands = 100000
two_like_cards_count = 0
three_like_cards_count = 0
full_house_count = 0
color_count = 0

for i in range(num_hands):
    hand = random.sample([(i,j) for i in range(1,5) for j in range(1,14)], 5)
    if two_like_cards(hand):
        two_like_cards_count += 1
    if three_like_cards(hand):
        three_like_cards_count += 1
    if full_house(hand):
        full_house_count += 1
    if color(hand):
        color_count += 1

# Compare with actual odds
two_like_cards_odds = 1/17.4
three_like_cards_odds = 1/46.3
full_house_odds = 1/694.2
color_odds = 1/509.8

print("tvenna:")
print(f"Simulated odds: {two_like_cards_count/num_hands}")
print(f"Actual odds: {two_like_cards_odds}\n")

print("þrenna:")
print(f"Simulated odds: {three_like_cards_count/num_hands}")
print(f"Actual odds: {three_like_cards_odds}\n")

print("Fullt hus:")
print(f"Simulated odds: {full_house_count/num_hands}")
print(f"Actual odds: {full_house_odds}\n")

print("lit:")
print(f"Simulated odds: {color_count/num_hands}")
print(f"Actual odds: {color_odds}")

"""Verkefni 36: Stærð jarðskjálfta
***

1, Skrifið fall sem reiknar (og skilar) stærð jarðskjálfta fyrir gefið vægi.
"""

import math

def jardskjalf(M0):

    M = 2/3 * (math.log10(M0) - 9.1)
    return round(M, 1)

M0 = 10**16
M = jardskjalf(M0)
print(f"stærð jarðskjálfta {M:.1f}")

"""2, 20. október 2020 varð stór jarðskjálfti nálægt Krýsuvík."""

import math

staerd = {
    "USGS": 3.20e17,
    "GCMT": 3.29e17,
    "GFZ": 3.20e17,
}

magnitude = {}
for center, energy in staerd.items():
    magnitude[center] = 2/3 * (math.log10(energy) - 9.1)

print("Miðstöð   Stærð")
print("–––––––––––––––")
for center, energy in staerd.items():
    mag = magnitude[center]
    print(f"{center:<8} {energy/1e17:.2f}e17   {mag:.2f}")

"""Verkefni 37: Valkvæðir stikar
***
"""

import math

def log(x, a=10):
    return math.log(x) / math.log(a)
print(log(100))
print(log(243, 3))
print(log(128, 2))

def print_with_nulls(lst, nulls=4):
    for i, num in enumerate(lst):
        num_str = "{:,.0f}".format(num)
        num_str = num_str.replace(",", "," + "0" * nulls)
        print(num_str, end="")
        if i < len(lst) - 1:
            print(",", end=" ")
    print()
import math

lst = [math.exp(x) for x in range(6)]
print_with_nulls(lst, 3)