# -*- coding: utf-8 -*-
"""t10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mHURO87hi-nzUFmb2g-ojLL-rfOD8AK2

Fyrri æfingin í kafla 13.5
***
"""

import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)

def f(x):
    return x * (x - 2) * (x - 4)

x = np.linspace(0, 4, 100)
y_true = f(x)

y_data = y_true + np.random.normal(0, 0.1, size=100)

p = np.polyfit(x, y_data, deg=3)
y_fit = np.polyval(p, x)

plt.scatter(x, y_data, label='Data')
plt.plot(x, y_fit, label='Fit')
plt.plot(x, y_true, label='True function')
plt.legend()
plt.show()

"""Seinni æfingin í kafla 13.5
***
"""

import numpy as np
import urllib.request
import statsmodels.api as sm

url = 'https://cs.hi.is/python/karfa.txt'
with urllib.request.urlopen(url) as response:
    data = np.loadtxt(response)

X = data[:, :-1]
y = data[:, -1]

X = sm.add_constant(X)

model = sm.OLS(y, X).fit()


print(model.summary())


print(f"Módelið er: hæð =  {model.params[0]:.3f} + {model.params[1]:.2f}*aldur + {model.params[2]:.2f}*þyngd")