# -*- coding: utf-8 -*-
"""T11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wQtIEIKQCdP85J-EkGO6trb92zv9RB0R

Skoðið fyrst (og keyrið) dæmið í bláa rammanum aftast í kafla 1.3 í nýja námsefninu.
***
"""

import numpy as np
import matplotlib.pyplot as plt
def f(x,y):
  f1 = 3/(1+(x-2)**2+4*(y-3)**2)
  f2 = 4/(1+x**2+y**2)
  return f1 - f2

x = np.linspace(-2,4)
y = np.linspace(-1,4)
(X,Y) = np.meshgrid(x,y)
Z = f(X,Y)
plt.set_cmap('rainbow')
plt.contour(X, Y, Z, linewidths=3)
plt.colorbar()
plt.grid('True')

"""VV7. Lágmörkun Rosenbrock-fallsins
***

Afritið forritið að ofan inn í Colab. Minnkið svæðið sem fallið er teiknað á um hálfa einingu á öllum hliðum, niður í ferninginn [−1.5,1.5]×[−0.5,2.5]. Prófið að fjölga hæðarlínunum. Reiknið líka fallsgildið í 𝑥0=(−1.2,1) sem ætti að vera 24.2 og 𝑥∗=(1,1) sem ætti að vera 0.
***
"""

def rosen(x):
    res = (1-x[0])**2 + 100*(x[1] - x[0]**2)**2
    return res

import matplotlib.pyplot as plt
import numpy as np
plt.figure(figsize=(8,8))
x = np.linspace(-1.5, 1.5, 800)
y = np.linspace(-0.5, 2.5, 1200)
[X,Y] = np.meshgrid(x,y)
Z = rosen([X,Y])
levels = np.linspace(0, 2000, 41)
c = plt.contour(X, Y, Z, levels = levels, colors = 'gray')
levstr = {l:str(l) for l in levels}
plt.clabel(c, fmt=levstr)
plt.xticks(range(-1, 2))
plt.yticks(range(0, 3))
plt.grid(True)

x0_val = rosen([-1.2, 1])
print("x0=(-1.2, 1):", x0_val)

xstar_val = rosen([1, 1])
print("x*=(1, 1):", xstar_val)

"""þar sem f er fallið sem á að lágmarka, x0 er vigur með byrjunarágiskun og xmin er lággildispunkturinn. Notið minimize til að lágmarka fall Rosenbrocks með 𝑥0=(−1.2,1). Skoðið hvað er í result og skrifið örfá orð um það.
***
"""

import scipy.optimize as opt

def rosen(x):
    return (1-x[0])**2 + 100*(x[1] - x[0]**2)**2

x0 = (-1.2, 1)
result = opt.minimize(rosen, x0)

print(result)

"""minimize getur tekið inn viðbótarstika callback=cb, og þá kallar það á cb(xk) með núverandi ítrekunargildi xk í hverri ítrekun (í þessu tilviki er xk tveggja staka vigur). Notið þennan „fídus“ til að teikna ítrekunargildin inn á hæðarlínumyndina (hægt er að láta cb kalla á plt.scatter(x[0],x[1]))
***
"""

def rosen(x):
    res = (1-x[0])**2 + 100*(x[1] - x[0]**2)**2
    return res

import matplotlib.pyplot as plt
import numpy as np
from scipy.optimize import minimize

plt.figure(figsize=(8,8))
x = np.linspace(-2,2,400)
y = np.linspace(-1,3,400)
[X,Y] = np.meshgrid(x,y)
Z = rosen([X,Y])
levels = [0.2, 5, 50] + list(range(200,2300,400))
c = plt.contour(X, Y, Z, levels = levels, colors = 'gray')
levstr = {l:str(l) for l in levels}
plt.clabel(c, fmt=levstr)
plt.xticks(range(-2,3))
plt.yticks(range(-1,4))
plt.grid("True")

def cb(xk):
    plt.scatter(xk[0], xk[1], color='r')

res = minimize(rosen, [0, 0], callback=cb)
plt.scatter(res.x[0], res.x[1], color='g')

"""minimize getur líka tekið inn stika method="aðferð", þar sem aðferð getur t.d. verið "L-BFGS-B", "CG", og "Powell" fyrir utan þá sjálfvöldu, "BFGS". Prófið og segið skipulega frá niðurstöðum. Prófið líka eina sjálfvalda aðferð (skoðið skjölun um minimize á netinu til að sjá möguleikana).
***
"""

import numpy as np
from scipy.optimize import minimize, rosen

x0 = np.array([0, 0])

methods = ['BFGS', 'L-BFGS-B', 'CG', 'Powell']

standalone_method = {'method': 'COBYLA'}

for method in methods + [standalone_method]:
    print(f"\n{method} Optimization")
    print("=" * 30)
    res = minimize(rosen, x0, method=method)
    print(f"Success: {res.success}")
    print(f"Function value: {res.fun}")
    print(f"Number of iterations: {res.nit}")
    print(f"Number of function evaluations: {res.nfev}")
    print(f"Solution: {res.x}")

"""Ákvarðið hlutafleiður og þar með stigul Rosenbrock-fallsins (á blaði) og forritið hann í Python falli rosg(x) sem skilar tveggja staka NumPy-vigri með stiglinum í punktinum 𝑥=(𝑥0,𝑥1). Ef rétt er forritað ætti stigullinn í 𝑥0 að vera (−215.6,−88) og í 𝑥=(1,1) ætti hann að vera (0,0).
***
"""

import numpy as np

def rosg(x):
    x0, x1 = x[0], x[1]
    dfdx0 = -2*(1 - x0) - 400*(x1 - x0**2)*x0
    dfdx1 = 200*(x1 - x0**2)
    return np.array([dfdx0, dfdx1])
rosg(np.array([1, 1]))

"""skil ekki alveg hvað á að gera í lið 6"""

