# -*- coding: utf-8 -*-
"""T3.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11IM9MwHeLjUY23_fz5faDsYV9zABB-wT

**F. Viðsnúningur lista**
***

1. Skrifið fall hali(L) sem skilar hala L, þ.e. lista með öllum stökum nema því fremsta.
"""

def hali(L):
    return L[1:]
svar=hali([1,2,3,4,5])
print(svar)

"""2. Skrifið fall hausaftast(L) sem skilar nýjum lista þar sem haus L hefur verið færður aftast. Ef kallað er með L=[1,2,3,4] ætti fallið að skila [2,3,4,1]."""

def header_last(L):
    return L[1:] + [L[0]]
svar = header_last([1,2,3,4])
print(svar)

"""3. Skrifið fall snúavið(L) sem snýr við lista."""

def snuavid(L):
    n = len(L)
    M = []
    for i in range(n-1, -1, -1):
        M.append(L[i])
    return M
svar= snuavid([1,2,3,4])
print(svar)

"""6  Meðaltal og staðalfrávik"""

import math

def statistics(x):
    n = len(x)
    m = sum(x) / n
    s = math.sqrt(sum((i - m)**2 for i in x) / (n - 1))
    return (m, s)
svar = statistics([3,7,7,1])
svar2 = statistics([1,3,2001])
print(svar)
print(svar2)

"""9  Innsetningarröðun og Pythontutor"""

#1 raða lista
def sort(A):
    B = A.copy()
    i = 1
    while i < len(B):
        j = i
        while j > 0 and B[j-1] > B[j]:
            B[j], B[j-1] = B[j-1], B[j]
            j -= 1
        i += 1
    return B

svar = sort([3,8,1,2,5,4])
print(svar)