# -*- coding: utf-8 -*-
"""T5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ChaktfGh2SmVlASaNaPBC8BBk5hrPObi

TÍMADÆMI 5

***

9.5.1  Dæmi um plot
***

Æfing: Stikar í plot
***
"""

from math import sqrt
import matplotlib.pyplot as plt

x = range(5)
y = [sqrt(t) for t in x]
plt.figure(figsize=(4, 1.8), dpi=120)
plt.plot(x, y, lw=3, ls='-', c='b', marker='x', ms=12)
plt.xlabel('x')
plt.ylabel('y = √x')
plt.show()

"""9.5.2  Dæmi um legend
***

Æfing:  Prófið svo að bæta við cos(x) með tilheyrandi label
***
"""

from math import pi, sin, cos
from random import random
t = [k*2*pi/20 for k in range(21)]
s = [sin(x) for x in t]
c = [cos(x) for x in t]
y = [random() for k in range(21)]
plt.figure(figsize=(5,2))
plt.plot(t, s, label='sin(x)')
plt.plot(t, c, label='cos(x)')
plt.plot(t, y, label='slembitölur')
plt.grid(True)
plt.legend();

"""Prófið líka að fjölga punktunum (það þarf að breyta bæði 20 og 21 í stærri tölur).
***
"""

from math import pi, sin, cos
from random import random
t = [k*2*pi/200 for k in range(201)]
s = [sin(x) for x in t]
c = [cos(x) for x in t]
y = [random() for k in range(201)]
plt.figure(figsize=(5,2))
plt.plot(t, s, label='sin(x)')
plt.plot(t, c, label='cos(x)')
plt.plot(t, y, label='slembitölur')
plt.grid(True)
plt.legend();

"""KAFLI 9.5.3
***

Æfing: Súlurit
***
"""

from random import gauss

x = [gauss(0,1) for i in range(5000)]

plt.figure(figsize = (6,3))
plt.hist(x, bins=25, range=(-3,3), rwidth=0.8, color='pink', ec='k');
plt.xlabel('x-gildi');
plt.ylabel('fjöldi');
plt.grid(True, axis='y')

"""KAFLI 9.6.4
***

X SIN X
"""

import numpy as np
import matplotlib.pyplot as plt

(a,b) = (-5, 2)
x = np.linspace(a,b)
plt.figure(figsize=(9,6))
plt.grid(True)
plt.axvline(color='k')
plt.axhline(color='k')
plt.box(False)
plt.plot(x, x * np.sin(x))
plt.xlim([a,b])
plt.tick_params(length=0)
plt.show()

"""𝑒−2𝑥+1
***
"""

from numpy import linspace
import matplotlib.pyplot as plt

(a,b) = (-5,2)
x = linspace(a,b)
plt.figure(figsize=(9,6))
plt.grid(True)
plt.axvline(c='k')
plt.axhline(c='k')
plt.box(False)
plt.plot(x, [np.exp(-2 * t + 1) for t in x])
plt.xlim([a,b])
plt.tick_params(length=0)
plt.show()

"""17  Dálkar í CSV-skrá
***
"""

with open("malmar.txt") as f:
    next(f)

    gogn = [(row.split()[0], float(row.split()[1])) for row in f]

print([f"{nafn} {thyngd}" for nafn, thyngd in gogn])