# -*- coding: utf-8 -*-
"""T6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ojvRzf3RkD8TYblGq0qHnglGMvUd_M6W

Æfingin í kafla 10.6.4: Allir Málmar
***
"""

import numpy as np
import matplotlib.pyplot as plt

skra = "https://cs.hi.is/python/allir-malmar.txt"
A = np.loadtxt(skra, skiprows=1, delimiter=';', dtype='str').T
efnatak = A[0].tolist()
nafn = A[1].tolist()
saetistala = A[2].astype(int)
eðlisþyngd = np.char.replace(A[3], ',', '.').astype(float)
braedslumark = A[4].astype(int)
enskt_nafn = A[5].tolist()


fig, ax = plt.subplots()
ax.scatter(saetistala, eðlisþyngd)
ax.set_xlabel('Sæti')
ax.set_ylabel('Eðlisþyngd')
ax.set_title('punktarit af sætistölu og eðlisþyngd')


fig, ax = plt.subplots()
ax.hist(braedslumark, bins=10)
ax.set_xlabel('Bræðslumark')
ax.set_ylabel('Frequency')
ax.set_title('Bræðslumark')

plt.show()

"""Verkefni 20: Numpy og vigrar
***
"""

import numpy as np
import numpy.linalg as la

x = np.array([6, 7, 18])
y = np.array([1, 1, 6])

# y - x
diff = y - x
print("y - x =", diff)

# 2y + x
sum = 2 * y + x
print("2y + x =", sum)

#(x + y) * (x - y)
mult = (x + y) * (x - y)
print("(x + y) * (x - y) =", mult)

# ‖𝑥‖2−‖𝑦‖2
norm_diff = la.norm(x) ** 2 - la.norm(y) ** 2
print("||x||^2 - ||y||^2 =", norm_diff)

# ‖𝑥+𝑦‖⋅‖𝑥−𝑦‖
norm_mult = la.norm(x + y) * la.norm(x - y)
print("||x + y|| * ||x - y|| =", norm_mult)

"""Verkefni 21: Raðað í íslenska stafrófsröð
***
"""

#1
def íslenska(s):
    """Key function to sort Icelandic alphabetically."""
    return [íslenska.k.get(c.lower(), 0) for c in s]

íslenska.a = list('0123456789aábcdðeéfghiíjklmnoópqrstuúvwxyýzþæö')
íslenska.k = dict(zip(íslenska.a, range(1, len(íslenska.a) + 1)))

# án þess að nota key
oradad = ["Ýmir", "Una", "Ása", "Örn", "Þór", "Már", "Mist"]
radad_random = sorted(oradad)
print("Raðað án key:", radad_random)

# Sort the list using the íslenska key function
radad_íslenska = sorted(oradad, key=íslenska)
print("raðaður listi (með íslenska key):", radad_íslenska)

#2
import numpy as np

data = np.genfromtxt('https://cs.hi.is/python/kennitolur.txt', delimiter=',', dtype=str)

nofn = list(data[:, 0])
prof_nr = list(data[:, 1])
kt = list(data[:, 2])

def islenska(s):
    """Key function to sort Icelandic alphabetically."""
    return [islenska.k.get(c.lower(), 0) for c in s]

islenska.a = list('0123456789aábcdðeéfghiíjklmnoópqrstuúvwxyýzþæö')
islenska.k = dict(zip(islenska.a, range(1, len(islenska.a) + 1)))

nafn_sorted = sorted(nofn, key=islenska)

for nafn in nafn_sorted:
    print(nafn)

#3
import numpy as np
from tabulate import tabulate

data = np.genfromtxt('https://cs.hi.is/python/kennitolur.txt', delimiter=',', dtype=str)

nofn = list(data[:, 0])
prof_nr = list(data[:, 1])
kt = list(data[:, 2])

def islenska(s):
    """Key function to sort Icelandic alphabetically."""
    return [islenska.k.get(c.lower(), 0) for c in s]

islenska.a = list('0123456789aábcdðeéfghiíjklmnoópqrstuúvwxyýzþæö')
islenska.k = dict(zip(islenska.a, range(1, len(islenska.a) + 1)))

nofn_sorted = sorted(nofn, key=islenska)

# Create lookup tables
prof_tafla = dict(zip(nofn, prof_nr))
kt_tafla = dict(zip(nofn, kt))

# Create table with headers
table = [["NAFN", "PROF NUMER", "KT"]]
for nafn in nofn_sorted:
    table.append([nafn, prof_tafla[nafn], kt_tafla[nafn]])

# Print table
print(tabulate(table, headers='firstrow'))