# -*- coding: utf-8 -*-
"""T8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iGiHtbxL0Y6lbgnUrCJ0vCbHrT98DPbH

## 1. Flatarmynd lýst með 2xn fylki

Búið til fylkið

$$ M = \begin{pmatrix}
0 & 3 & 3 & 0 & 0 & \text{nan} & 1 & 2 \\
0 & 0 & 2 & 2 & 0 & \text{nan} & 1 & 1
\end{pmatrix}$$

og teiknið myndina sem það lýsir (rétthyrningur með striki). Notið svo 30°-skekkingarfylki til að breyta honum í samsíðung og teiknið hann.
"""

import matplotlib.pyplot as plt
import numpy as np

def teikna_fylki(A):
    plt.plot(A[0],A[1], lw=3, color='k')

M = np.array([[0, 3, 3, 0, 0, np.nan, 1, 2],
              [0, 0, 2, 2, 0, np.nan, 1, 1]])

S = np.array([[1, np.tan(np.deg2rad(30))], [0, 1]])
MS = S @ M

plt.axis("equal")
teikna_fylki(M)
teikna_fylki(MS)
plt.show()

"""## 2. Snúningsfylki
Skrifið fall sem skilar snúningsfylki fyrir almennt horn og snúningspunktinn $(0,0)$. Notið það til að snúa rétthyrningnum í lið 1 og teiknið útkomuna.
"""

import numpy as np
import matplotlib.pyplot as plt

def rotation_matrix(angle):
    c, s = np.cos(angle), np.sin(angle)
    return np.array([[c, -s], [s, c]])

rect = np.array([[1, 1], [3, 1], [3, 2], [1, 2], [1, 1]])

angle = np.pi/4
rotation_point = np.array([1, 1.5])

centroid = np.mean(rect, axis=0)
translated_rect = rect - centroid

translated_rotation_point = rotation_point - centroid

R = rotation_matrix(angle)
rotated_rect = np.dot(R, translated_rect.T).T

rotated_rotation_point = np.dot(R, translated_rotation_point)

final_rect = rotated_rect + centroid
final_rotation_point = rotated_rotation_point + centroid

plt.plot(rect[:,0], rect[:,1], 'b', label='Byrjun')
plt.plot(final_rect[:,0], final_rect[:,1], 'r', label='Rotated')
plt.plot(final_rotation_point[0], final_rotation_point[1], 'ko', label='Rotation Point')
plt.axis('equal')
plt.legend()
plt.show()

"""## 3. Sammiðja rétthyrningar
Búið til fylki fyrir rétthyrning sem er 5 x 3 að stærð með minni rétthyrning sem er 3 x 1 að stærð í miðjunni (stærri rétthyrningurinn hefur neðra vinstra horn í $(0,0)$ en sá minni í $(1,1)$). Teiknið myndina sem kemur út með `teikna_fylki`.
"""

import matplotlib.pyplot as plt
import numpy as np

arr = np.zeros((5, 3))

arr[1:4, 1] = 1

plt.imshow(arr, cmap='gray', interpolation='nearest', origin='lower')
plt.xticks(range(3), range(3))
plt.yticks(range(5), range(5))
plt.grid(color='w', linestyle='-', linewidth=2)
plt.show()

"""## 4. Þríhyrningur með hæð

Búið til fylki T sem lýsir þríhyrningi með hornpunkta $A = (1,0)$, $B = (3,2)$ og $C = (4,0)$ með lóðréttu striki (hæð) frá $B$ niður á hliðina $AC$. Teiknið.
"""

import numpy as np
import matplotlib.pyplot as plt

A = np.array([1, 0])
B = np.array([3, 2])
C = np.array([4, 0])

h = (B[1] - A[1]) * (C[0] - A[0]) / (C[1] - A[1])
D = np.array([A[0] + h, B[1]])

T = np.array([A, B, C, D, A])

plt.plot(T[:,0], T[:,1])
plt.plot([B[0], D[0]], [B[1], D[1]])
plt.axis('equal')
plt.show()

"""## 5. Hliðra–snúa–hliðra
Búið til fall sem notar snúningsfylkisfallið úr lið 2 ásamt fallinu `hliðra` til að snúa um almennt horn og almennan punkt. Notið það til að snúa þríhyrningnum í lið 4 um 180° um punktinn B og teiknið bæði upphaflega þríhyrninginn og þann snúna inn á sömu mynd.
"""

import numpy as np
import matplotlib.pyplot as plt

def rotation_matrix(angle):
    return np.array([[np.cos(angle), -np.sin(angle)],
                     [np.sin(angle), np.cos(angle)]])

def gates(angle, point):
    return np.array([point[0]*np.cos(angle) - point[1]*np.sin(angle),
                     point[0]*np.sin(angle) + point[1]*np.cos(angle)])

def rotate_around_point(angle, point, center):
    return gates(angle, point-center) + center

A = np.array([1, 2])
B = np.array([3, 1])
C = np.array([4, 3])

A_rotated = rotate_around_point(np.pi, A, B)
B_rotated = B
C_rotated = rotate_around_point(np.pi, C, B)

plt.plot([A[0], B[0]], [A[1], B[1]], 'b-', label='byrjun')
plt.plot([B[0], C[0]], [B[1], C[1]], 'b-')
plt.plot([A_rotated[0], B_rotated[0]], [A_rotated[1], B_rotated[1]], 'r-', label='rotated')
plt.plot([B_rotated[0], C_rotated[0]], [B_rotated[1], C_rotated[1]], 'r-')
plt.plot(B[0], B[1], 'ko')
plt.legend()
plt.axis('equal')
plt.show()

"""## 6. Snúa–spegla–snúa
Búið nú til fall sem speglar um gefna línu $y = ax$ með því að snúa, spegla og snúa til baka (notið helst fylkjamargföldun). Hornið sem línan myndar við x-ás fæst með $\arctan a$. Prófið að spegla þríhyrningnum í lið 4 um línuna $y = x$.

"""

import numpy as np

def mirror_about_line(point, a):
    angle = np.arctan(a)
    flip_matrix = np.array([[1, 0], [0, -1]])
    rotation_matrix = np.array([[np.cos(angle), -np.sin(angle)],
                                [np.sin(angle), np.cos(angle)]])
    flip_back_matrix = np.array([[1, 0], [0, -1]])
    reflection_matrix = flip_matrix @ rotation_matrix @ flip_back_matrix
    return reflection_matrix @ point

A = np.array([1, 2])
B = np.array([3, 1])
C = np.array([4, 3])

a = 1

A_mirrored = mirror_about_line(A, a)
B_mirrored = mirror_about_line(B, a)
C_mirrored = mirror_about_line(C, a)

plt.plot([A[0], B[0]], [A[1], B[1]], 'b-', label='byrjun')
plt.plot([B[0], C[0]], [B[1], C[1]], 'b-')
plt.plot([A_mirrored[0], B_mirrored[0]], [A_mirrored[1], B_mirrored[1]], 'r-', label='speglað')
plt.plot([B_mirrored[0], C_mirrored[0]], [B_mirrored[1], C_mirrored[1]], 'r-')
plt.plot([A[0], A_mirrored[0]], [A[1], A_mirrored[1]], 'k:')
plt.plot([B[0], B_mirrored[0]], [B[1], B_mirrored[1]], 'k:')
plt.plot([C[0], C_mirrored[0]], [C[1], C_mirrored[1]], 'k:')
plt.legend()
plt.axis('equal')
plt.show()

"""33  Leslie-fylki og gröf
***

Búið til Lesley-fylki (með NumPy) og ákvarðið stofnstærð í byrjun og á hverju ári næstu sjö ár.
"""

import numpy as np

L = np.array([[0.1, 0.3, 0.5, 0.4, 0.1],
              [0.1, 0.1, 0.2, 0.4, 1.0],
              [0., 0.1, 0.1, 0.2, 0.],
              [0., 0., 0.3, 0.1, 0.],
              [0., 0., 0., 0.3, 0.]])

P0 = np.array([100, 200, 300, 200, 200])

P = np.zeros((8, 5))
P[0] = P0
for i in range(1, 8):
    P[i] = L @ P[i-1]

np.set_printoptions(precision=0, suppress=True)

print("Population size:")
print(P)

"""Mun stofninn að lokum deyja út?
já, íbúafjöldinn muni að lokum deyja út.
***

Teiknið mynd af fæðingar- og dánartíðninni á þessa leið (línubreidd er 3 punktar):
***
"""

import matplotlib.pyplot as plt
import numpy as np

birth_rates = np.array([0.1, 0.3, 0.5, 0.4, 0.1])
death_rates = np.array([0.1, 0.1, 0.2, 0.4, 1.0])

fig, ax = plt.subplots()

ax.plot(birth_rates, linewidth=3, label='fæðingartíðni')
ax.plot(death_rates, linewidth=3, label='dánartíðni')

ax.set_xlabel('aldur')
ax.set_ylabel('fjöldi')
ax.legend()

plt.show()